// Code generated by counterfeiter. DO NOT EDIT.
package prooffakes

import (
	"context"
	"source-score/pkg/api"
	"source-score/pkg/domain/proof"
	"sync"
)

type FakeClaimReader struct {
	GetClaimByUriDigestStub        func(context.Context, string) (*api.Claim, error)
	getClaimByUriDigestMutex       sync.RWMutex
	getClaimByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getClaimByUriDigestReturns struct {
		result1 *api.Claim
		result2 error
	}
	getClaimByUriDigestReturnsOnCall map[int]struct {
		result1 *api.Claim
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClaimReader) GetClaimByUriDigest(arg1 context.Context, arg2 string) (*api.Claim, error) {
	fake.getClaimByUriDigestMutex.Lock()
	ret, specificReturn := fake.getClaimByUriDigestReturnsOnCall[len(fake.getClaimByUriDigestArgsForCall)]
	fake.getClaimByUriDigestArgsForCall = append(fake.getClaimByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetClaimByUriDigestStub
	fakeReturns := fake.getClaimByUriDigestReturns
	fake.recordInvocation("GetClaimByUriDigest", []interface{}{arg1, arg2})
	fake.getClaimByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClaimReader) GetClaimByUriDigestCallCount() int {
	fake.getClaimByUriDigestMutex.RLock()
	defer fake.getClaimByUriDigestMutex.RUnlock()
	return len(fake.getClaimByUriDigestArgsForCall)
}

func (fake *FakeClaimReader) GetClaimByUriDigestCalls(stub func(context.Context, string) (*api.Claim, error)) {
	fake.getClaimByUriDigestMutex.Lock()
	defer fake.getClaimByUriDigestMutex.Unlock()
	fake.GetClaimByUriDigestStub = stub
}

func (fake *FakeClaimReader) GetClaimByUriDigestArgsForCall(i int) (context.Context, string) {
	fake.getClaimByUriDigestMutex.RLock()
	defer fake.getClaimByUriDigestMutex.RUnlock()
	argsForCall := fake.getClaimByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClaimReader) GetClaimByUriDigestReturns(result1 *api.Claim, result2 error) {
	fake.getClaimByUriDigestMutex.Lock()
	defer fake.getClaimByUriDigestMutex.Unlock()
	fake.GetClaimByUriDigestStub = nil
	fake.getClaimByUriDigestReturns = struct {
		result1 *api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimReader) GetClaimByUriDigestReturnsOnCall(i int, result1 *api.Claim, result2 error) {
	fake.getClaimByUriDigestMutex.Lock()
	defer fake.getClaimByUriDigestMutex.Unlock()
	fake.GetClaimByUriDigestStub = nil
	if fake.getClaimByUriDigestReturnsOnCall == nil {
		fake.getClaimByUriDigestReturnsOnCall = make(map[int]struct {
			result1 *api.Claim
			result2 error
		})
	}
	fake.getClaimByUriDigestReturnsOnCall[i] = struct {
		result1 *api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClaimReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ proof.ClaimReader = new(FakeClaimReader)
