// Code generated by counterfeiter. DO NOT EDIT.
package prooffakes

import (
	"context"
	"source-score/pkg/api"
	"source-score/pkg/domain/proof"
	"sync"
)

type FakeProofService struct {
	DeleteProofByUriDigestStub        func(context.Context, string) error
	deleteProofByUriDigestMutex       sync.RWMutex
	deleteProofByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	deleteProofByUriDigestReturns struct {
		result1 error
	}
	deleteProofByUriDigestReturnsOnCall map[int]struct {
		result1 error
	}
	GetProofByUriDigestStub        func(context.Context, string) (*api.Proof, error)
	getProofByUriDigestMutex       sync.RWMutex
	getProofByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getProofByUriDigestReturns struct {
		result1 *api.Proof
		result2 error
	}
	getProofByUriDigestReturnsOnCall map[int]struct {
		result1 *api.Proof
		result2 error
	}
	GetProofsStub        func(context.Context) ([]api.Proof, error)
	getProofsMutex       sync.RWMutex
	getProofsArgsForCall []struct {
		arg1 context.Context
	}
	getProofsReturns struct {
		result1 []api.Proof
		result2 error
	}
	getProofsReturnsOnCall map[int]struct {
		result1 []api.Proof
		result2 error
	}
	GetProofsByClaimDigestStub        func(context.Context, string) ([]api.Proof, error)
	getProofsByClaimDigestMutex       sync.RWMutex
	getProofsByClaimDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getProofsByClaimDigestReturns struct {
		result1 []api.Proof
		result2 error
	}
	getProofsByClaimDigestReturnsOnCall map[int]struct {
		result1 []api.Proof
		result2 error
	}
	GetProofsByClaimsStub        func(context.Context) (map[string][]api.Proof, error)
	getProofsByClaimsMutex       sync.RWMutex
	getProofsByClaimsArgsForCall []struct {
		arg1 context.Context
	}
	getProofsByClaimsReturns struct {
		result1 map[string][]api.Proof
		result2 error
	}
	getProofsByClaimsReturnsOnCall map[int]struct {
		result1 map[string][]api.Proof
		result2 error
	}
	PatchProofByUriDigestStub        func(context.Context, *api.ProofPatchInput, string) error
	patchProofByUriDigestMutex       sync.RWMutex
	patchProofByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 *api.ProofPatchInput
		arg3 string
	}
	patchProofByUriDigestReturns struct {
		result1 error
	}
	patchProofByUriDigestReturnsOnCall map[int]struct {
		result1 error
	}
	PostProofStub        func(context.Context, *api.ProofInput) (string, error)
	postProofMutex       sync.RWMutex
	postProofArgsForCall []struct {
		arg1 context.Context
		arg2 *api.ProofInput
	}
	postProofReturns struct {
		result1 string
		result2 error
	}
	postProofReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProofService) DeleteProofByUriDigest(arg1 context.Context, arg2 string) error {
	fake.deleteProofByUriDigestMutex.Lock()
	ret, specificReturn := fake.deleteProofByUriDigestReturnsOnCall[len(fake.deleteProofByUriDigestArgsForCall)]
	fake.deleteProofByUriDigestArgsForCall = append(fake.deleteProofByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DeleteProofByUriDigestStub
	fakeReturns := fake.deleteProofByUriDigestReturns
	fake.recordInvocation("DeleteProofByUriDigest", []interface{}{arg1, arg2})
	fake.deleteProofByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProofService) DeleteProofByUriDigestCallCount() int {
	fake.deleteProofByUriDigestMutex.RLock()
	defer fake.deleteProofByUriDigestMutex.RUnlock()
	return len(fake.deleteProofByUriDigestArgsForCall)
}

func (fake *FakeProofService) DeleteProofByUriDigestCalls(stub func(context.Context, string) error) {
	fake.deleteProofByUriDigestMutex.Lock()
	defer fake.deleteProofByUriDigestMutex.Unlock()
	fake.DeleteProofByUriDigestStub = stub
}

func (fake *FakeProofService) DeleteProofByUriDigestArgsForCall(i int) (context.Context, string) {
	fake.deleteProofByUriDigestMutex.RLock()
	defer fake.deleteProofByUriDigestMutex.RUnlock()
	argsForCall := fake.deleteProofByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProofService) DeleteProofByUriDigestReturns(result1 error) {
	fake.deleteProofByUriDigestMutex.Lock()
	defer fake.deleteProofByUriDigestMutex.Unlock()
	fake.DeleteProofByUriDigestStub = nil
	fake.deleteProofByUriDigestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProofService) DeleteProofByUriDigestReturnsOnCall(i int, result1 error) {
	fake.deleteProofByUriDigestMutex.Lock()
	defer fake.deleteProofByUriDigestMutex.Unlock()
	fake.DeleteProofByUriDigestStub = nil
	if fake.deleteProofByUriDigestReturnsOnCall == nil {
		fake.deleteProofByUriDigestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteProofByUriDigestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProofService) GetProofByUriDigest(arg1 context.Context, arg2 string) (*api.Proof, error) {
	fake.getProofByUriDigestMutex.Lock()
	ret, specificReturn := fake.getProofByUriDigestReturnsOnCall[len(fake.getProofByUriDigestArgsForCall)]
	fake.getProofByUriDigestArgsForCall = append(fake.getProofByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetProofByUriDigestStub
	fakeReturns := fake.getProofByUriDigestReturns
	fake.recordInvocation("GetProofByUriDigest", []interface{}{arg1, arg2})
	fake.getProofByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProofService) GetProofByUriDigestCallCount() int {
	fake.getProofByUriDigestMutex.RLock()
	defer fake.getProofByUriDigestMutex.RUnlock()
	return len(fake.getProofByUriDigestArgsForCall)
}

func (fake *FakeProofService) GetProofByUriDigestCalls(stub func(context.Context, string) (*api.Proof, error)) {
	fake.getProofByUriDigestMutex.Lock()
	defer fake.getProofByUriDigestMutex.Unlock()
	fake.GetProofByUriDigestStub = stub
}

func (fake *FakeProofService) GetProofByUriDigestArgsForCall(i int) (context.Context, string) {
	fake.getProofByUriDigestMutex.RLock()
	defer fake.getProofByUriDigestMutex.RUnlock()
	argsForCall := fake.getProofByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProofService) GetProofByUriDigestReturns(result1 *api.Proof, result2 error) {
	fake.getProofByUriDigestMutex.Lock()
	defer fake.getProofByUriDigestMutex.Unlock()
	fake.GetProofByUriDigestStub = nil
	fake.getProofByUriDigestReturns = struct {
		result1 *api.Proof
		result2 error
	}{result1, result2}
}

func (fake *FakeProofService) GetProofByUriDigestReturnsOnCall(i int, result1 *api.Proof, result2 error) {
	fake.getProofByUriDigestMutex.Lock()
	defer fake.getProofByUriDigestMutex.Unlock()
	fake.GetProofByUriDigestStub = nil
	if fake.getProofByUriDigestReturnsOnCall == nil {
		fake.getProofByUriDigestReturnsOnCall = make(map[int]struct {
			result1 *api.Proof
			result2 error
		})
	}
	fake.getProofByUriDigestReturnsOnCall[i] = struct {
		result1 *api.Proof
		result2 error
	}{result1, result2}
}

func (fake *FakeProofService) GetProofs(arg1 context.Context) ([]api.Proof, error) {
	fake.getProofsMutex.Lock()
	ret, specificReturn := fake.getProofsReturnsOnCall[len(fake.getProofsArgsForCall)]
	fake.getProofsArgsForCall = append(fake.getProofsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetProofsStub
	fakeReturns := fake.getProofsReturns
	fake.recordInvocation("GetProofs", []interface{}{arg1})
	fake.getProofsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProofService) GetProofsCallCount() int {
	fake.getProofsMutex.RLock()
	defer fake.getProofsMutex.RUnlock()
	return len(fake.getProofsArgsForCall)
}

func (fake *FakeProofService) GetProofsCalls(stub func(context.Context) ([]api.Proof, error)) {
	fake.getProofsMutex.Lock()
	defer fake.getProofsMutex.Unlock()
	fake.GetProofsStub = stub
}

func (fake *FakeProofService) GetProofsArgsForCall(i int) context.Context {
	fake.getProofsMutex.RLock()
	defer fake.getProofsMutex.RUnlock()
	argsForCall := fake.getProofsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProofService) GetProofsReturns(result1 []api.Proof, result2 error) {
	fake.getProofsMutex.Lock()
	defer fake.getProofsMutex.Unlock()
	fake.GetProofsStub = nil
	fake.getProofsReturns = struct {
		result1 []api.Proof
		result2 error
	}{result1, result2}
}

func (fake *FakeProofService) GetProofsReturnsOnCall(i int, result1 []api.Proof, result2 error) {
	fake.getProofsMutex.Lock()
	defer fake.getProofsMutex.Unlock()
	fake.GetProofsStub = nil
	if fake.getProofsReturnsOnCall == nil {
		fake.getProofsReturnsOnCall = make(map[int]struct {
			result1 []api.Proof
			result2 error
		})
	}
	fake.getProofsReturnsOnCall[i] = struct {
		result1 []api.Proof
		result2 error
	}{result1, result2}
}

func (fake *FakeProofService) GetProofsByClaimDigest(arg1 context.Context, arg2 string) ([]api.Proof, error) {
	fake.getProofsByClaimDigestMutex.Lock()
	ret, specificReturn := fake.getProofsByClaimDigestReturnsOnCall[len(fake.getProofsByClaimDigestArgsForCall)]
	fake.getProofsByClaimDigestArgsForCall = append(fake.getProofsByClaimDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetProofsByClaimDigestStub
	fakeReturns := fake.getProofsByClaimDigestReturns
	fake.recordInvocation("GetProofsByClaimDigest", []interface{}{arg1, arg2})
	fake.getProofsByClaimDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProofService) GetProofsByClaimDigestCallCount() int {
	fake.getProofsByClaimDigestMutex.RLock()
	defer fake.getProofsByClaimDigestMutex.RUnlock()
	return len(fake.getProofsByClaimDigestArgsForCall)
}

func (fake *FakeProofService) GetProofsByClaimDigestCalls(stub func(context.Context, string) ([]api.Proof, error)) {
	fake.getProofsByClaimDigestMutex.Lock()
	defer fake.getProofsByClaimDigestMutex.Unlock()
	fake.GetProofsByClaimDigestStub = stub
}

func (fake *FakeProofService) GetProofsByClaimDigestArgsForCall(i int) (context.Context, string) {
	fake.getProofsByClaimDigestMutex.RLock()
	defer fake.getProofsByClaimDigestMutex.RUnlock()
	argsForCall := fake.getProofsByClaimDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProofService) GetProofsByClaimDigestReturns(result1 []api.Proof, result2 error) {
	fake.getProofsByClaimDigestMutex.Lock()
	defer fake.getProofsByClaimDigestMutex.Unlock()
	fake.GetProofsByClaimDigestStub = nil
	fake.getProofsByClaimDigestReturns = struct {
		result1 []api.Proof
		result2 error
	}{result1, result2}
}

func (fake *FakeProofService) GetProofsByClaimDigestReturnsOnCall(i int, result1 []api.Proof, result2 error) {
	fake.getProofsByClaimDigestMutex.Lock()
	defer fake.getProofsByClaimDigestMutex.Unlock()
	fake.GetProofsByClaimDigestStub = nil
	if fake.getProofsByClaimDigestReturnsOnCall == nil {
		fake.getProofsByClaimDigestReturnsOnCall = make(map[int]struct {
			result1 []api.Proof
			result2 error
		})
	}
	fake.getProofsByClaimDigestReturnsOnCall[i] = struct {
		result1 []api.Proof
		result2 error
	}{result1, result2}
}

func (fake *FakeProofService) GetProofsByClaims(arg1 context.Context) (map[string][]api.Proof, error) {
	fake.getProofsByClaimsMutex.Lock()
	ret, specificReturn := fake.getProofsByClaimsReturnsOnCall[len(fake.getProofsByClaimsArgsForCall)]
	fake.getProofsByClaimsArgsForCall = append(fake.getProofsByClaimsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetProofsByClaimsStub
	fakeReturns := fake.getProofsByClaimsReturns
	fake.recordInvocation("GetProofsByClaims", []interface{}{arg1})
	fake.getProofsByClaimsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProofService) GetProofsByClaimsCallCount() int {
	fake.getProofsByClaimsMutex.RLock()
	defer fake.getProofsByClaimsMutex.RUnlock()
	return len(fake.getProofsByClaimsArgsForCall)
}

func (fake *FakeProofService) GetProofsByClaimsCalls(stub func(context.Context) (map[string][]api.Proof, error)) {
	fake.getProofsByClaimsMutex.Lock()
	defer fake.getProofsByClaimsMutex.Unlock()
	fake.GetProofsByClaimsStub = stub
}

func (fake *FakeProofService) GetProofsByClaimsArgsForCall(i int) context.Context {
	fake.getProofsByClaimsMutex.RLock()
	defer fake.getProofsByClaimsMutex.RUnlock()
	argsForCall := fake.getProofsByClaimsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProofService) GetProofsByClaimsReturns(result1 map[string][]api.Proof, result2 error) {
	fake.getProofsByClaimsMutex.Lock()
	defer fake.getProofsByClaimsMutex.Unlock()
	fake.GetProofsByClaimsStub = nil
	fake.getProofsByClaimsReturns = struct {
		result1 map[string][]api.Proof
		result2 error
	}{result1, result2}
}

func (fake *FakeProofService) GetProofsByClaimsReturnsOnCall(i int, result1 map[string][]api.Proof, result2 error) {
	fake.getProofsByClaimsMutex.Lock()
	defer fake.getProofsByClaimsMutex.Unlock()
	fake.GetProofsByClaimsStub = nil
	if fake.getProofsByClaimsReturnsOnCall == nil {
		fake.getProofsByClaimsReturnsOnCall = make(map[int]struct {
			result1 map[string][]api.Proof
			result2 error
		})
	}
	fake.getProofsByClaimsReturnsOnCall[i] = struct {
		result1 map[string][]api.Proof
		result2 error
	}{result1, result2}
}

func (fake *FakeProofService) PatchProofByUriDigest(arg1 context.Context, arg2 *api.ProofPatchInput, arg3 string) error {
	fake.patchProofByUriDigestMutex.Lock()
	ret, specificReturn := fake.patchProofByUriDigestReturnsOnCall[len(fake.patchProofByUriDigestArgsForCall)]
	fake.patchProofByUriDigestArgsForCall = append(fake.patchProofByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 *api.ProofPatchInput
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.PatchProofByUriDigestStub
	fakeReturns := fake.patchProofByUriDigestReturns
	fake.recordInvocation("PatchProofByUriDigest", []interface{}{arg1, arg2, arg3})
	fake.patchProofByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProofService) PatchProofByUriDigestCallCount() int {
	fake.patchProofByUriDigestMutex.RLock()
	defer fake.patchProofByUriDigestMutex.RUnlock()
	return len(fake.patchProofByUriDigestArgsForCall)
}

func (fake *FakeProofService) PatchProofByUriDigestCalls(stub func(context.Context, *api.ProofPatchInput, string) error) {
	fake.patchProofByUriDigestMutex.Lock()
	defer fake.patchProofByUriDigestMutex.Unlock()
	fake.PatchProofByUriDigestStub = stub
}

func (fake *FakeProofService) PatchProofByUriDigestArgsForCall(i int) (context.Context, *api.ProofPatchInput, string) {
	fake.patchProofByUriDigestMutex.RLock()
	defer fake.patchProofByUriDigestMutex.RUnlock()
	argsForCall := fake.patchProofByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProofService) PatchProofByUriDigestReturns(result1 error) {
	fake.patchProofByUriDigestMutex.Lock()
	defer fake.patchProofByUriDigestMutex.Unlock()
	fake.PatchProofByUriDigestStub = nil
	fake.patchProofByUriDigestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProofService) PatchProofByUriDigestReturnsOnCall(i int, result1 error) {
	fake.patchProofByUriDigestMutex.Lock()
	defer fake.patchProofByUriDigestMutex.Unlock()
	fake.PatchProofByUriDigestStub = nil
	if fake.patchProofByUriDigestReturnsOnCall == nil {
		fake.patchProofByUriDigestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.patchProofByUriDigestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProofService) PostProof(arg1 context.Context, arg2 *api.ProofInput) (string, error) {
	fake.postProofMutex.Lock()
	ret, specificReturn := fake.postProofReturnsOnCall[len(fake.postProofArgsForCall)]
	fake.postProofArgsForCall = append(fake.postProofArgsForCall, struct {
		arg1 context.Context
		arg2 *api.ProofInput
	}{arg1, arg2})
	stub := fake.PostProofStub
	fakeReturns := fake.postProofReturns
	fake.recordInvocation("PostProof", []interface{}{arg1, arg2})
	fake.postProofMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProofService) PostProofCallCount() int {
	fake.postProofMutex.RLock()
	defer fake.postProofMutex.RUnlock()
	return len(fake.postProofArgsForCall)
}

func (fake *FakeProofService) PostProofCalls(stub func(context.Context, *api.ProofInput) (string, error)) {
	fake.postProofMutex.Lock()
	defer fake.postProofMutex.Unlock()
	fake.PostProofStub = stub
}

func (fake *FakeProofService) PostProofArgsForCall(i int) (context.Context, *api.ProofInput) {
	fake.postProofMutex.RLock()
	defer fake.postProofMutex.RUnlock()
	argsForCall := fake.postProofArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProofService) PostProofReturns(result1 string, result2 error) {
	fake.postProofMutex.Lock()
	defer fake.postProofMutex.Unlock()
	fake.PostProofStub = nil
	fake.postProofReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeProofService) PostProofReturnsOnCall(i int, result1 string, result2 error) {
	fake.postProofMutex.Lock()
	defer fake.postProofMutex.Unlock()
	fake.PostProofStub = nil
	if fake.postProofReturnsOnCall == nil {
		fake.postProofReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.postProofReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeProofService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProofService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ proof.ProofService = new(FakeProofService)
