// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Claim Complete claim entity with verification status
type Claim struct {
	// Checked Indicates whether the claim has been verified
	Checked bool `binding:"required" json:"checked"`

	// SourceUriDigest SHA-256 hash of the parent source URI
	SourceUriDigest string `binding:"required" json:"sourceUriDigest"`

	// Summary Detailed description of the claim
	Summary string `binding:"required" json:"summary"`

	// Title Short title of the claim
	Title string `binding:"required" json:"title"`

	// Uri Unique HTTPS URL of the claim
	Uri string `binding:"required" json:"uri"`

	// UriDigest SHA-256 hash of the URI, used as primary key
	UriDigest string `binding:"required" gorm:"primaryKey" json:"uriDigest"`

	// Validity Indicates whether the claim is valid (true) or invalid (false) based on proof analysis
	Validity bool `binding:"required" json:"validity"`
}

// ClaimInput Input schema for creating a new claim
type ClaimInput struct {
	// SourceUriDigest SHA-256 hash of the parent source URI
	SourceUriDigest string `binding:"required" json:"sourceUriDigest" validate:"nonempty"`

	// Summary Detailed description of the claim
	Summary string `binding:"required" json:"summary" validate:"nonempty"`

	// Title Short title of the claim
	Title string `binding:"required" json:"title" validate:"nonempty"`

	// Uri Unique HTTPS URL identifying the claim
	Uri string `binding:"required" json:"uri" validate:"httpsurl"`
}

// ClaimPatchInput Input schema for partially updating a claim
type ClaimPatchInput struct {
	// Summary Updated detailed description
	Summary *string `json:"summary" validate:"omitnil,nonempty"`

	// Title Updated short title
	Title *string `json:"title" validate:"omitnil,nonempty"`
}

// ClaimVerification Input schema for manually verifying a claim
type ClaimVerification struct {
	// Validity Whether the claim is valid (true) or invalid (false)
	Validity *bool `binding:"required" json:"validity,omitempty" validate:"nonempty"`
}

// CreateSourceResponse Response after successfully creating a source
type CreateSourceResponse struct {
	// UriDigest SHA-256 hash of the source URI
	UriDigest string `binding:"required" json:"uriDigest"`
}

// Proof Complete proof entity
type Proof struct {
	// ClaimUriDigest SHA-256 hash of the claim URI
	ClaimUriDigest string `binding:"required" json:"claimUriDigest"`

	// ReviewedBy Identifier of the reviewer
	ReviewedBy string `binding:"required" json:"reviewedBy"`

	// SupportsClaim Whether this proof supports (true) or refutes (false) the claim
	SupportsClaim bool `binding:"required" json:"supportsClaim"`

	// Uri Unique HTTPS URL of the proof source
	Uri string `binding:"required" json:"uri"`

	// UriDigest SHA-256 hash of the URI, used as primary key
	UriDigest string `binding:"required" gorm:"primaryKey" json:"uriDigest"`
}

// ProofInput Input schema for creating a new proof
type ProofInput struct {
	// ClaimUriDigest SHA-256 hash of the claim URI being evaluated (no spaces allowed)
	ClaimUriDigest string `binding:"required" json:"claimUriDigest" validate:"nonempty,nospace"`

	// ReviewedBy Identifier of the reviewer who evaluated this proof (no spaces allowed)
	ReviewedBy string `binding:"required" json:"reviewedBy" validate:"nonempty,nospace"`

	// SupportsClaim Whether this proof supports (true) or refutes (false) the claim
	SupportsClaim *bool `binding:"required" json:"supportsClaim,omitempty" validate:"nonempty"`

	// Uri Unique HTTPS URL of the proof source
	Uri string `binding:"required" json:"uri" validate:"httpsurl"`
}

// ProofPatchInput Input schema for updating proof reviewer
type ProofPatchInput struct {
	// ReviewedBy Updated reviewer identifier (no spaces allowed)
	ReviewedBy string `binding:"required" json:"reviewedBy" validate:"nonempty,nospace"`
}

// Source Complete source entity with calculated credibility score
type Source struct {
	// Name Display name of the source
	Name string `binding:"required" json:"name"`

	// Score Credibility score (0.0 to 1.0) calculated as ratio of valid to total verified claims
	Score float64 `binding:"required" json:"score"`

	// Summary Brief description of the source
	Summary string `binding:"required" json:"summary"`

	// Tags Comma-separated categorization tags
	Tags string `binding:"required" json:"tags"`

	// Uri Unique HTTPS URL of the source
	Uri string `binding:"required" json:"uri"`

	// UriDigest SHA-256 hash of the URI, used as primary key
	UriDigest string `binding:"required" gorm:"primaryKey" json:"uriDigest"`
}

// SourceInput Input schema for creating a new source
type SourceInput struct {
	// Name Display name of the information source
	Name string `binding:"required" json:"name" validate:"nonempty"`

	// Summary Brief description of the source
	Summary string `binding:"required" json:"summary" validate:"nonempty"`

	// Tags Comma-separated tags for categorization (no spaces allowed)
	Tags string `binding:"required" json:"tags" validate:"nonempty,nospace"`

	// Uri Unique HTTPS URL identifying the source
	Uri string `binding:"required" json:"uri" validate:"httpsurl"`
}

// SourcePatchInput Input schema for partially updating a source
type SourcePatchInput struct {
	// Name Updated display name
	Name *string `json:"name" validate:"omitnil,nonempty"`

	// Summary Updated description
	Summary *string `json:"summary" validate:"omitnil,nonempty"`

	// Tags Updated comma-separated tags (no spaces allowed)
	Tags *string `json:"tags" validate:"omitnil,nospace,nonempty"`
}

// PostClaimJSONRequestBody defines body for PostClaim for application/json ContentType.
type PostClaimJSONRequestBody = ClaimInput

// PatchClaimJSONRequestBody defines body for PatchClaim for application/json ContentType.
type PatchClaimJSONRequestBody = ClaimPatchInput

// VerifyClaimJSONRequestBody defines body for VerifyClaim for application/json ContentType.
type VerifyClaimJSONRequestBody = ClaimVerification

// PostProofJSONRequestBody defines body for PostProof for application/json ContentType.
type PostProofJSONRequestBody = ProofInput

// PatchProofJSONRequestBody defines body for PatchProof for application/json ContentType.
type PatchProofJSONRequestBody = ProofPatchInput

// PostSourceJSONRequestBody defines body for PostSource for application/json ContentType.
type PostSourceJSONRequestBody = SourceInput

// PatchSourceJSONRequestBody defines body for PatchSource for application/json ContentType.
type PatchSourceJSONRequestBody = SourcePatchInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new claim
	// (POST /api/v1/claim)
	PostClaim(c *gin.Context)
	// Delete a claim
	// (DELETE /api/v1/claim/{uriDigest})
	DeleteClaim(c *gin.Context, uriDigest string)
	// Get claim by URI digest
	// (GET /api/v1/claim/{uriDigest})
	GetClaim(c *gin.Context, uriDigest string)
	// Update claim fields
	// (PATCH /api/v1/claim/{uriDigest})
	PatchClaim(c *gin.Context, uriDigest string)
	// Verify a single claim
	// (POST /api/v1/claim/{uriDigest})
	VerifyClaim(c *gin.Context, uriDigest string)
	// Get all claims
	// (GET /api/v1/claims)
	GetClaims(c *gin.Context)
	// Verify all claims
	// (POST /api/v1/claims/verify)
	VerifyAllClaims(c *gin.Context)
	// Create a new proof
	// (POST /api/v1/proof)
	PostProof(c *gin.Context)
	// Delete a proof
	// (DELETE /api/v1/proof/{uriDigest})
	DeleteProof(c *gin.Context, uriDigest string)
	// Get proof by URI digest
	// (GET /api/v1/proof/{uriDigest})
	GetProof(c *gin.Context, uriDigest string)
	// Update proof reviewer
	// (PATCH /api/v1/proof/{uriDigest})
	PatchProof(c *gin.Context, uriDigest string)
	// Get all proofs
	// (GET /api/v1/proofs)
	GetProofs(c *gin.Context)
	// Create a new source
	// (POST /api/v1/source)
	PostSource(c *gin.Context)
	// Delete a source
	// (DELETE /api/v1/source/{uriDigest})
	DeleteSource(c *gin.Context, uriDigest string)
	// Get source by URI digest
	// (GET /api/v1/source/{uriDigest})
	GetSource(c *gin.Context, uriDigest string)
	// Update source fields
	// (PATCH /api/v1/source/{uriDigest})
	PatchSource(c *gin.Context, uriDigest string)
	// Get all sources
	// (GET /api/v1/sources)
	GetSources(c *gin.Context)
	// Update all source scores
	// (POST /api/v1/sources/scores)
	UpdateAllScores(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostClaim operation middleware
func (siw *ServerInterfaceWrapper) PostClaim(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostClaim(c)
}

// DeleteClaim operation middleware
func (siw *ServerInterfaceWrapper) DeleteClaim(c *gin.Context) {

	var err error

	// ------------- Path parameter "uriDigest" -------------
	var uriDigest string

	err = runtime.BindStyledParameterWithOptions("simple", "uriDigest", c.Param("uriDigest"), &uriDigest, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uriDigest: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteClaim(c, uriDigest)
}

// GetClaim operation middleware
func (siw *ServerInterfaceWrapper) GetClaim(c *gin.Context) {

	var err error

	// ------------- Path parameter "uriDigest" -------------
	var uriDigest string

	err = runtime.BindStyledParameterWithOptions("simple", "uriDigest", c.Param("uriDigest"), &uriDigest, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uriDigest: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClaim(c, uriDigest)
}

// PatchClaim operation middleware
func (siw *ServerInterfaceWrapper) PatchClaim(c *gin.Context) {

	var err error

	// ------------- Path parameter "uriDigest" -------------
	var uriDigest string

	err = runtime.BindStyledParameterWithOptions("simple", "uriDigest", c.Param("uriDigest"), &uriDigest, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uriDigest: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchClaim(c, uriDigest)
}

// VerifyClaim operation middleware
func (siw *ServerInterfaceWrapper) VerifyClaim(c *gin.Context) {

	var err error

	// ------------- Path parameter "uriDigest" -------------
	var uriDigest string

	err = runtime.BindStyledParameterWithOptions("simple", "uriDigest", c.Param("uriDigest"), &uriDigest, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uriDigest: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VerifyClaim(c, uriDigest)
}

// GetClaims operation middleware
func (siw *ServerInterfaceWrapper) GetClaims(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClaims(c)
}

// VerifyAllClaims operation middleware
func (siw *ServerInterfaceWrapper) VerifyAllClaims(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VerifyAllClaims(c)
}

// PostProof operation middleware
func (siw *ServerInterfaceWrapper) PostProof(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProof(c)
}

// DeleteProof operation middleware
func (siw *ServerInterfaceWrapper) DeleteProof(c *gin.Context) {

	var err error

	// ------------- Path parameter "uriDigest" -------------
	var uriDigest string

	err = runtime.BindStyledParameterWithOptions("simple", "uriDigest", c.Param("uriDigest"), &uriDigest, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uriDigest: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteProof(c, uriDigest)
}

// GetProof operation middleware
func (siw *ServerInterfaceWrapper) GetProof(c *gin.Context) {

	var err error

	// ------------- Path parameter "uriDigest" -------------
	var uriDigest string

	err = runtime.BindStyledParameterWithOptions("simple", "uriDigest", c.Param("uriDigest"), &uriDigest, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uriDigest: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProof(c, uriDigest)
}

// PatchProof operation middleware
func (siw *ServerInterfaceWrapper) PatchProof(c *gin.Context) {

	var err error

	// ------------- Path parameter "uriDigest" -------------
	var uriDigest string

	err = runtime.BindStyledParameterWithOptions("simple", "uriDigest", c.Param("uriDigest"), &uriDigest, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uriDigest: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchProof(c, uriDigest)
}

// GetProofs operation middleware
func (siw *ServerInterfaceWrapper) GetProofs(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProofs(c)
}

// PostSource operation middleware
func (siw *ServerInterfaceWrapper) PostSource(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSource(c)
}

// DeleteSource operation middleware
func (siw *ServerInterfaceWrapper) DeleteSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "uriDigest" -------------
	var uriDigest string

	err = runtime.BindStyledParameterWithOptions("simple", "uriDigest", c.Param("uriDigest"), &uriDigest, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uriDigest: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteSource(c, uriDigest)
}

// GetSource operation middleware
func (siw *ServerInterfaceWrapper) GetSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "uriDigest" -------------
	var uriDigest string

	err = runtime.BindStyledParameterWithOptions("simple", "uriDigest", c.Param("uriDigest"), &uriDigest, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uriDigest: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSource(c, uriDigest)
}

// PatchSource operation middleware
func (siw *ServerInterfaceWrapper) PatchSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "uriDigest" -------------
	var uriDigest string

	err = runtime.BindStyledParameterWithOptions("simple", "uriDigest", c.Param("uriDigest"), &uriDigest, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uriDigest: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchSource(c, uriDigest)
}

// GetSources operation middleware
func (siw *ServerInterfaceWrapper) GetSources(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSources(c)
}

// UpdateAllScores operation middleware
func (siw *ServerInterfaceWrapper) UpdateAllScores(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAllScores(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/claim", wrapper.PostClaim)
	router.DELETE(options.BaseURL+"/api/v1/claim/:uriDigest", wrapper.DeleteClaim)
	router.GET(options.BaseURL+"/api/v1/claim/:uriDigest", wrapper.GetClaim)
	router.PATCH(options.BaseURL+"/api/v1/claim/:uriDigest", wrapper.PatchClaim)
	router.POST(options.BaseURL+"/api/v1/claim/:uriDigest", wrapper.VerifyClaim)
	router.GET(options.BaseURL+"/api/v1/claims", wrapper.GetClaims)
	router.POST(options.BaseURL+"/api/v1/claims/verify", wrapper.VerifyAllClaims)
	router.POST(options.BaseURL+"/api/v1/proof", wrapper.PostProof)
	router.DELETE(options.BaseURL+"/api/v1/proof/:uriDigest", wrapper.DeleteProof)
	router.GET(options.BaseURL+"/api/v1/proof/:uriDigest", wrapper.GetProof)
	router.PATCH(options.BaseURL+"/api/v1/proof/:uriDigest", wrapper.PatchProof)
	router.GET(options.BaseURL+"/api/v1/proofs", wrapper.GetProofs)
	router.POST(options.BaseURL+"/api/v1/source", wrapper.PostSource)
	router.DELETE(options.BaseURL+"/api/v1/source/:uriDigest", wrapper.DeleteSource)
	router.GET(options.BaseURL+"/api/v1/source/:uriDigest", wrapper.GetSource)
	router.PATCH(options.BaseURL+"/api/v1/source/:uriDigest", wrapper.PatchSource)
	router.GET(options.BaseURL+"/api/v1/sources", wrapper.GetSources)
	router.POST(options.BaseURL+"/api/v1/sources/scores", wrapper.UpdateAllScores)
}
