apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cnpg_database.namespace }}

---
apiVersion: v1
data:
  password: {{ .Values.cnpg_cluster.password | b64enc | quote }}
  username: {{ .Values.cnpg_cluster.username | b64enc | quote }}
kind: Secret
metadata:
  name: app-user-auth
  namespace: {{ .Values.cnpg_database.namespace }}
type: kubernetes.io/basic-auth

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-init-sql-db-setup
  namespace: {{ .Values.cnpg_database.namespace }}
data:
  sql.commands:
    {{ (.Files.Get "files/tables.sql") | indent 4 }}
    {{ (.Files.Get "files/permissions.sql") | indent 4 }}

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cnpg_cluster.name }}
  namespace: {{ .Values.cnpg_database.namespace }}
spec:
  instances: {{ .Values.cnpg_cluster.instanceCount }}
  storage:
    size: {{ .Values.cnpg_cluster.storageSize }}
  bootstrap:
    initdb:
      database: {{ .Values.cnpg_database.name }}
      owner: {{ .Values.cnpg_cluster.username }}
      secret:
        name: app-user-auth
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: post-init-sql-db-setup
          key: sql.commands

---
apiVersion: v1
kind: Pod
metadata:
  name: adminer
  namespace: {{ .Values.cnpg_database.namespace }}
spec:
  containers:
  - name: adminer
    image: adminer:4.8.1
    limits:
      memory: "256Mi"
    requests:
      cpu: "50m"
    ports:
    - containerPort: 8080