apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cnpgDatabase.namespace }}

---
apiVersion: v1
data:
  password: {{ .Values.cnpgCluster.superuserPassword | b64enc | quote }}
  username: {{ .Values.cnpgCluster.superuserName | b64enc | quote }}
kind: Secret
metadata:
  name: cnpg-superuser
  namespace: {{ .Values.cnpgDatabase.namespace }}
type: kubernetes.io/basic-auth

---
apiVersion: v1
data:
  password: {{ .Values.cnpgDatabase.userPassword | b64enc | quote }}
  username: {{ .Values.cnpgDatabase.username | b64enc | quote }}
kind: Secret
metadata:
  name: cnpg-user
  namespace: {{ .Values.cnpgDatabase.namespace }}
type: kubernetes.io/basic-auth

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-init-sql-db-setup
  namespace: {{ .Values.cnpgDatabase.namespace }}
data:
  sql.commands:
    {{ (.Files.Get "files/tables.sql") | indent 4 }}
    {{ (.Files.Get "files/permissions.sql") | indent 4 }}

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cnpgCluster.name }}
  namespace: {{ .Values.cnpgDatabase.namespace }}
spec:
  enableSuperuserAccess: true
  superuserSecret:
    name: cnpg-superuser
  instances: {{ .Values.cnpgCluster.instanceCount }}
  storage:
    size: {{ .Values.cnpgCluster.storageSize }}
  bootstrap:
    initdb:
      database: {{ .Values.cnpgDatabase.name }}
      owner: {{ .Values.cnpgDatabase.username }}
      secret:
        name: cnpg-user
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: post-init-sql-db-setup
          key: sql.commands

---
apiVersion: v1
kind: Pod
metadata:
  name: adminer
  namespace: {{ .Values.cnpgDatabase.namespace }}
spec:
  containers:
  - name: adminer
    image: adminer:latest
    resources:
      limits:
        memory: "256Mi"
      requests:
        cpu: "50m"
    ports:
    - containerPort: 8080