// Code generated by counterfeiter. DO NOT EDIT.
package sourcefakes

import (
	"context"
	"source-score/pkg/api"
	"source-score/pkg/domain/source"
	"sync"
)

type FakeSourceRepository struct {
	DeleteSourceByUriDigestStub        func(context.Context, *api.Source) error
	deleteSourceByUriDigestMutex       sync.RWMutex
	deleteSourceByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 *api.Source
	}
	deleteSourceByUriDigestReturns struct {
		result1 error
	}
	deleteSourceByUriDigestReturnsOnCall map[int]struct {
		result1 error
	}
	GetSourceByUriDigestStub        func(context.Context, string) (*api.Source, error)
	getSourceByUriDigestMutex       sync.RWMutex
	getSourceByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getSourceByUriDigestReturns struct {
		result1 *api.Source
		result2 error
	}
	getSourceByUriDigestReturnsOnCall map[int]struct {
		result1 *api.Source
		result2 error
	}
	GetSourcesStub        func(context.Context) ([]api.Source, error)
	getSourcesMutex       sync.RWMutex
	getSourcesArgsForCall []struct {
		arg1 context.Context
	}
	getSourcesReturns struct {
		result1 []api.Source
		result2 error
	}
	getSourcesReturnsOnCall map[int]struct {
		result1 []api.Source
		result2 error
	}
	PatchSourceByUriDigestStub        func(context.Context, *api.SourcePatchInput, string) error
	patchSourceByUriDigestMutex       sync.RWMutex
	patchSourceByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 *api.SourcePatchInput
		arg3 string
	}
	patchSourceByUriDigestReturns struct {
		result1 error
	}
	patchSourceByUriDigestReturnsOnCall map[int]struct {
		result1 error
	}
	PostSourceStub        func(context.Context, *api.SourceInput) (string, error)
	postSourceMutex       sync.RWMutex
	postSourceArgsForCall []struct {
		arg1 context.Context
		arg2 *api.SourceInput
	}
	postSourceReturns struct {
		result1 string
		result2 error
	}
	postSourceReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	UpdateSourceScoresStub        func(context.Context, *[]api.Source) error
	updateSourceScoresMutex       sync.RWMutex
	updateSourceScoresArgsForCall []struct {
		arg1 context.Context
		arg2 *[]api.Source
	}
	updateSourceScoresReturns struct {
		result1 error
	}
	updateSourceScoresReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSourceRepository) DeleteSourceByUriDigest(arg1 context.Context, arg2 *api.Source) error {
	fake.deleteSourceByUriDigestMutex.Lock()
	ret, specificReturn := fake.deleteSourceByUriDigestReturnsOnCall[len(fake.deleteSourceByUriDigestArgsForCall)]
	fake.deleteSourceByUriDigestArgsForCall = append(fake.deleteSourceByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 *api.Source
	}{arg1, arg2})
	stub := fake.DeleteSourceByUriDigestStub
	fakeReturns := fake.deleteSourceByUriDigestReturns
	fake.recordInvocation("DeleteSourceByUriDigest", []interface{}{arg1, arg2})
	fake.deleteSourceByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSourceRepository) DeleteSourceByUriDigestCallCount() int {
	fake.deleteSourceByUriDigestMutex.RLock()
	defer fake.deleteSourceByUriDigestMutex.RUnlock()
	return len(fake.deleteSourceByUriDigestArgsForCall)
}

func (fake *FakeSourceRepository) DeleteSourceByUriDigestCalls(stub func(context.Context, *api.Source) error) {
	fake.deleteSourceByUriDigestMutex.Lock()
	defer fake.deleteSourceByUriDigestMutex.Unlock()
	fake.DeleteSourceByUriDigestStub = stub
}

func (fake *FakeSourceRepository) DeleteSourceByUriDigestArgsForCall(i int) (context.Context, *api.Source) {
	fake.deleteSourceByUriDigestMutex.RLock()
	defer fake.deleteSourceByUriDigestMutex.RUnlock()
	argsForCall := fake.deleteSourceByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSourceRepository) DeleteSourceByUriDigestReturns(result1 error) {
	fake.deleteSourceByUriDigestMutex.Lock()
	defer fake.deleteSourceByUriDigestMutex.Unlock()
	fake.DeleteSourceByUriDigestStub = nil
	fake.deleteSourceByUriDigestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepository) DeleteSourceByUriDigestReturnsOnCall(i int, result1 error) {
	fake.deleteSourceByUriDigestMutex.Lock()
	defer fake.deleteSourceByUriDigestMutex.Unlock()
	fake.DeleteSourceByUriDigestStub = nil
	if fake.deleteSourceByUriDigestReturnsOnCall == nil {
		fake.deleteSourceByUriDigestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteSourceByUriDigestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepository) GetSourceByUriDigest(arg1 context.Context, arg2 string) (*api.Source, error) {
	fake.getSourceByUriDigestMutex.Lock()
	ret, specificReturn := fake.getSourceByUriDigestReturnsOnCall[len(fake.getSourceByUriDigestArgsForCall)]
	fake.getSourceByUriDigestArgsForCall = append(fake.getSourceByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetSourceByUriDigestStub
	fakeReturns := fake.getSourceByUriDigestReturns
	fake.recordInvocation("GetSourceByUriDigest", []interface{}{arg1, arg2})
	fake.getSourceByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSourceRepository) GetSourceByUriDigestCallCount() int {
	fake.getSourceByUriDigestMutex.RLock()
	defer fake.getSourceByUriDigestMutex.RUnlock()
	return len(fake.getSourceByUriDigestArgsForCall)
}

func (fake *FakeSourceRepository) GetSourceByUriDigestCalls(stub func(context.Context, string) (*api.Source, error)) {
	fake.getSourceByUriDigestMutex.Lock()
	defer fake.getSourceByUriDigestMutex.Unlock()
	fake.GetSourceByUriDigestStub = stub
}

func (fake *FakeSourceRepository) GetSourceByUriDigestArgsForCall(i int) (context.Context, string) {
	fake.getSourceByUriDigestMutex.RLock()
	defer fake.getSourceByUriDigestMutex.RUnlock()
	argsForCall := fake.getSourceByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSourceRepository) GetSourceByUriDigestReturns(result1 *api.Source, result2 error) {
	fake.getSourceByUriDigestMutex.Lock()
	defer fake.getSourceByUriDigestMutex.Unlock()
	fake.GetSourceByUriDigestStub = nil
	fake.getSourceByUriDigestReturns = struct {
		result1 *api.Source
		result2 error
	}{result1, result2}
}

func (fake *FakeSourceRepository) GetSourceByUriDigestReturnsOnCall(i int, result1 *api.Source, result2 error) {
	fake.getSourceByUriDigestMutex.Lock()
	defer fake.getSourceByUriDigestMutex.Unlock()
	fake.GetSourceByUriDigestStub = nil
	if fake.getSourceByUriDigestReturnsOnCall == nil {
		fake.getSourceByUriDigestReturnsOnCall = make(map[int]struct {
			result1 *api.Source
			result2 error
		})
	}
	fake.getSourceByUriDigestReturnsOnCall[i] = struct {
		result1 *api.Source
		result2 error
	}{result1, result2}
}

func (fake *FakeSourceRepository) GetSources(arg1 context.Context) ([]api.Source, error) {
	fake.getSourcesMutex.Lock()
	ret, specificReturn := fake.getSourcesReturnsOnCall[len(fake.getSourcesArgsForCall)]
	fake.getSourcesArgsForCall = append(fake.getSourcesArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetSourcesStub
	fakeReturns := fake.getSourcesReturns
	fake.recordInvocation("GetSources", []interface{}{arg1})
	fake.getSourcesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSourceRepository) GetSourcesCallCount() int {
	fake.getSourcesMutex.RLock()
	defer fake.getSourcesMutex.RUnlock()
	return len(fake.getSourcesArgsForCall)
}

func (fake *FakeSourceRepository) GetSourcesCalls(stub func(context.Context) ([]api.Source, error)) {
	fake.getSourcesMutex.Lock()
	defer fake.getSourcesMutex.Unlock()
	fake.GetSourcesStub = stub
}

func (fake *FakeSourceRepository) GetSourcesArgsForCall(i int) context.Context {
	fake.getSourcesMutex.RLock()
	defer fake.getSourcesMutex.RUnlock()
	argsForCall := fake.getSourcesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSourceRepository) GetSourcesReturns(result1 []api.Source, result2 error) {
	fake.getSourcesMutex.Lock()
	defer fake.getSourcesMutex.Unlock()
	fake.GetSourcesStub = nil
	fake.getSourcesReturns = struct {
		result1 []api.Source
		result2 error
	}{result1, result2}
}

func (fake *FakeSourceRepository) GetSourcesReturnsOnCall(i int, result1 []api.Source, result2 error) {
	fake.getSourcesMutex.Lock()
	defer fake.getSourcesMutex.Unlock()
	fake.GetSourcesStub = nil
	if fake.getSourcesReturnsOnCall == nil {
		fake.getSourcesReturnsOnCall = make(map[int]struct {
			result1 []api.Source
			result2 error
		})
	}
	fake.getSourcesReturnsOnCall[i] = struct {
		result1 []api.Source
		result2 error
	}{result1, result2}
}

func (fake *FakeSourceRepository) PatchSourceByUriDigest(arg1 context.Context, arg2 *api.SourcePatchInput, arg3 string) error {
	fake.patchSourceByUriDigestMutex.Lock()
	ret, specificReturn := fake.patchSourceByUriDigestReturnsOnCall[len(fake.patchSourceByUriDigestArgsForCall)]
	fake.patchSourceByUriDigestArgsForCall = append(fake.patchSourceByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 *api.SourcePatchInput
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.PatchSourceByUriDigestStub
	fakeReturns := fake.patchSourceByUriDigestReturns
	fake.recordInvocation("PatchSourceByUriDigest", []interface{}{arg1, arg2, arg3})
	fake.patchSourceByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSourceRepository) PatchSourceByUriDigestCallCount() int {
	fake.patchSourceByUriDigestMutex.RLock()
	defer fake.patchSourceByUriDigestMutex.RUnlock()
	return len(fake.patchSourceByUriDigestArgsForCall)
}

func (fake *FakeSourceRepository) PatchSourceByUriDigestCalls(stub func(context.Context, *api.SourcePatchInput, string) error) {
	fake.patchSourceByUriDigestMutex.Lock()
	defer fake.patchSourceByUriDigestMutex.Unlock()
	fake.PatchSourceByUriDigestStub = stub
}

func (fake *FakeSourceRepository) PatchSourceByUriDigestArgsForCall(i int) (context.Context, *api.SourcePatchInput, string) {
	fake.patchSourceByUriDigestMutex.RLock()
	defer fake.patchSourceByUriDigestMutex.RUnlock()
	argsForCall := fake.patchSourceByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSourceRepository) PatchSourceByUriDigestReturns(result1 error) {
	fake.patchSourceByUriDigestMutex.Lock()
	defer fake.patchSourceByUriDigestMutex.Unlock()
	fake.PatchSourceByUriDigestStub = nil
	fake.patchSourceByUriDigestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepository) PatchSourceByUriDigestReturnsOnCall(i int, result1 error) {
	fake.patchSourceByUriDigestMutex.Lock()
	defer fake.patchSourceByUriDigestMutex.Unlock()
	fake.PatchSourceByUriDigestStub = nil
	if fake.patchSourceByUriDigestReturnsOnCall == nil {
		fake.patchSourceByUriDigestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.patchSourceByUriDigestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepository) PostSource(arg1 context.Context, arg2 *api.SourceInput) (string, error) {
	fake.postSourceMutex.Lock()
	ret, specificReturn := fake.postSourceReturnsOnCall[len(fake.postSourceArgsForCall)]
	fake.postSourceArgsForCall = append(fake.postSourceArgsForCall, struct {
		arg1 context.Context
		arg2 *api.SourceInput
	}{arg1, arg2})
	stub := fake.PostSourceStub
	fakeReturns := fake.postSourceReturns
	fake.recordInvocation("PostSource", []interface{}{arg1, arg2})
	fake.postSourceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSourceRepository) PostSourceCallCount() int {
	fake.postSourceMutex.RLock()
	defer fake.postSourceMutex.RUnlock()
	return len(fake.postSourceArgsForCall)
}

func (fake *FakeSourceRepository) PostSourceCalls(stub func(context.Context, *api.SourceInput) (string, error)) {
	fake.postSourceMutex.Lock()
	defer fake.postSourceMutex.Unlock()
	fake.PostSourceStub = stub
}

func (fake *FakeSourceRepository) PostSourceArgsForCall(i int) (context.Context, *api.SourceInput) {
	fake.postSourceMutex.RLock()
	defer fake.postSourceMutex.RUnlock()
	argsForCall := fake.postSourceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSourceRepository) PostSourceReturns(result1 string, result2 error) {
	fake.postSourceMutex.Lock()
	defer fake.postSourceMutex.Unlock()
	fake.PostSourceStub = nil
	fake.postSourceReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeSourceRepository) PostSourceReturnsOnCall(i int, result1 string, result2 error) {
	fake.postSourceMutex.Lock()
	defer fake.postSourceMutex.Unlock()
	fake.PostSourceStub = nil
	if fake.postSourceReturnsOnCall == nil {
		fake.postSourceReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.postSourceReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeSourceRepository) UpdateSourceScores(arg1 context.Context, arg2 *[]api.Source) error {
	fake.updateSourceScoresMutex.Lock()
	ret, specificReturn := fake.updateSourceScoresReturnsOnCall[len(fake.updateSourceScoresArgsForCall)]
	fake.updateSourceScoresArgsForCall = append(fake.updateSourceScoresArgsForCall, struct {
		arg1 context.Context
		arg2 *[]api.Source
	}{arg1, arg2})
	stub := fake.UpdateSourceScoresStub
	fakeReturns := fake.updateSourceScoresReturns
	fake.recordInvocation("UpdateSourceScores", []interface{}{arg1, arg2})
	fake.updateSourceScoresMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSourceRepository) UpdateSourceScoresCallCount() int {
	fake.updateSourceScoresMutex.RLock()
	defer fake.updateSourceScoresMutex.RUnlock()
	return len(fake.updateSourceScoresArgsForCall)
}

func (fake *FakeSourceRepository) UpdateSourceScoresCalls(stub func(context.Context, *[]api.Source) error) {
	fake.updateSourceScoresMutex.Lock()
	defer fake.updateSourceScoresMutex.Unlock()
	fake.UpdateSourceScoresStub = stub
}

func (fake *FakeSourceRepository) UpdateSourceScoresArgsForCall(i int) (context.Context, *[]api.Source) {
	fake.updateSourceScoresMutex.RLock()
	defer fake.updateSourceScoresMutex.RUnlock()
	argsForCall := fake.updateSourceScoresArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSourceRepository) UpdateSourceScoresReturns(result1 error) {
	fake.updateSourceScoresMutex.Lock()
	defer fake.updateSourceScoresMutex.Unlock()
	fake.UpdateSourceScoresStub = nil
	fake.updateSourceScoresReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepository) UpdateSourceScoresReturnsOnCall(i int, result1 error) {
	fake.updateSourceScoresMutex.Lock()
	defer fake.updateSourceScoresMutex.Unlock()
	fake.UpdateSourceScoresStub = nil
	if fake.updateSourceScoresReturnsOnCall == nil {
		fake.updateSourceScoresReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateSourceScoresReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSourceRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ source.SourceRepository = new(FakeSourceRepository)
