// Code generated by counterfeiter. DO NOT EDIT.
package sourcefakes

import (
	"context"
	"source-score/pkg/api"
	"source-score/pkg/domain/source"
	"sync"
)

type FakeSourceRepoInterface struct {
	DeleteSourceByUriDigestStub        func(context.Context, *api.Source) error
	deleteSourceByUriDigestMutex       sync.RWMutex
	deleteSourceByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 *api.Source
	}
	deleteSourceByUriDigestReturns struct {
		result1 error
	}
	deleteSourceByUriDigestReturnsOnCall map[int]struct {
		result1 error
	}
	GetSourceByUriDigestStub        func(context.Context, string) (*api.Source, error)
	getSourceByUriDigestMutex       sync.RWMutex
	getSourceByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getSourceByUriDigestReturns struct {
		result1 *api.Source
		result2 error
	}
	getSourceByUriDigestReturnsOnCall map[int]struct {
		result1 *api.Source
		result2 error
	}
	PutSourceStub        func(context.Context, *api.SourceInput) error
	putSourceMutex       sync.RWMutex
	putSourceArgsForCall []struct {
		arg1 context.Context
		arg2 *api.SourceInput
	}
	putSourceReturns struct {
		result1 error
	}
	putSourceReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateSourceByUriDigestStub        func(context.Context, *api.SourceInput, string) error
	updateSourceByUriDigestMutex       sync.RWMutex
	updateSourceByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 *api.SourceInput
		arg3 string
	}
	updateSourceByUriDigestReturns struct {
		result1 error
	}
	updateSourceByUriDigestReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSourceRepoInterface) DeleteSourceByUriDigest(arg1 context.Context, arg2 *api.Source) error {
	fake.deleteSourceByUriDigestMutex.Lock()
	ret, specificReturn := fake.deleteSourceByUriDigestReturnsOnCall[len(fake.deleteSourceByUriDigestArgsForCall)]
	fake.deleteSourceByUriDigestArgsForCall = append(fake.deleteSourceByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 *api.Source
	}{arg1, arg2})
	stub := fake.DeleteSourceByUriDigestStub
	fakeReturns := fake.deleteSourceByUriDigestReturns
	fake.recordInvocation("DeleteSourceByUriDigest", []interface{}{arg1, arg2})
	fake.deleteSourceByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSourceRepoInterface) DeleteSourceByUriDigestCallCount() int {
	fake.deleteSourceByUriDigestMutex.RLock()
	defer fake.deleteSourceByUriDigestMutex.RUnlock()
	return len(fake.deleteSourceByUriDigestArgsForCall)
}

func (fake *FakeSourceRepoInterface) DeleteSourceByUriDigestCalls(stub func(context.Context, *api.Source) error) {
	fake.deleteSourceByUriDigestMutex.Lock()
	defer fake.deleteSourceByUriDigestMutex.Unlock()
	fake.DeleteSourceByUriDigestStub = stub
}

func (fake *FakeSourceRepoInterface) DeleteSourceByUriDigestArgsForCall(i int) (context.Context, *api.Source) {
	fake.deleteSourceByUriDigestMutex.RLock()
	defer fake.deleteSourceByUriDigestMutex.RUnlock()
	argsForCall := fake.deleteSourceByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSourceRepoInterface) DeleteSourceByUriDigestReturns(result1 error) {
	fake.deleteSourceByUriDigestMutex.Lock()
	defer fake.deleteSourceByUriDigestMutex.Unlock()
	fake.DeleteSourceByUriDigestStub = nil
	fake.deleteSourceByUriDigestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepoInterface) DeleteSourceByUriDigestReturnsOnCall(i int, result1 error) {
	fake.deleteSourceByUriDigestMutex.Lock()
	defer fake.deleteSourceByUriDigestMutex.Unlock()
	fake.DeleteSourceByUriDigestStub = nil
	if fake.deleteSourceByUriDigestReturnsOnCall == nil {
		fake.deleteSourceByUriDigestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteSourceByUriDigestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepoInterface) GetSourceByUriDigest(arg1 context.Context, arg2 string) (*api.Source, error) {
	fake.getSourceByUriDigestMutex.Lock()
	ret, specificReturn := fake.getSourceByUriDigestReturnsOnCall[len(fake.getSourceByUriDigestArgsForCall)]
	fake.getSourceByUriDigestArgsForCall = append(fake.getSourceByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetSourceByUriDigestStub
	fakeReturns := fake.getSourceByUriDigestReturns
	fake.recordInvocation("GetSourceByUriDigest", []interface{}{arg1, arg2})
	fake.getSourceByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSourceRepoInterface) GetSourceByUriDigestCallCount() int {
	fake.getSourceByUriDigestMutex.RLock()
	defer fake.getSourceByUriDigestMutex.RUnlock()
	return len(fake.getSourceByUriDigestArgsForCall)
}

func (fake *FakeSourceRepoInterface) GetSourceByUriDigestCalls(stub func(context.Context, string) (*api.Source, error)) {
	fake.getSourceByUriDigestMutex.Lock()
	defer fake.getSourceByUriDigestMutex.Unlock()
	fake.GetSourceByUriDigestStub = stub
}

func (fake *FakeSourceRepoInterface) GetSourceByUriDigestArgsForCall(i int) (context.Context, string) {
	fake.getSourceByUriDigestMutex.RLock()
	defer fake.getSourceByUriDigestMutex.RUnlock()
	argsForCall := fake.getSourceByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSourceRepoInterface) GetSourceByUriDigestReturns(result1 *api.Source, result2 error) {
	fake.getSourceByUriDigestMutex.Lock()
	defer fake.getSourceByUriDigestMutex.Unlock()
	fake.GetSourceByUriDigestStub = nil
	fake.getSourceByUriDigestReturns = struct {
		result1 *api.Source
		result2 error
	}{result1, result2}
}

func (fake *FakeSourceRepoInterface) GetSourceByUriDigestReturnsOnCall(i int, result1 *api.Source, result2 error) {
	fake.getSourceByUriDigestMutex.Lock()
	defer fake.getSourceByUriDigestMutex.Unlock()
	fake.GetSourceByUriDigestStub = nil
	if fake.getSourceByUriDigestReturnsOnCall == nil {
		fake.getSourceByUriDigestReturnsOnCall = make(map[int]struct {
			result1 *api.Source
			result2 error
		})
	}
	fake.getSourceByUriDigestReturnsOnCall[i] = struct {
		result1 *api.Source
		result2 error
	}{result1, result2}
}

func (fake *FakeSourceRepoInterface) PutSource(arg1 context.Context, arg2 *api.SourceInput) error {
	fake.putSourceMutex.Lock()
	ret, specificReturn := fake.putSourceReturnsOnCall[len(fake.putSourceArgsForCall)]
	fake.putSourceArgsForCall = append(fake.putSourceArgsForCall, struct {
		arg1 context.Context
		arg2 *api.SourceInput
	}{arg1, arg2})
	stub := fake.PutSourceStub
	fakeReturns := fake.putSourceReturns
	fake.recordInvocation("PutSource", []interface{}{arg1, arg2})
	fake.putSourceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSourceRepoInterface) PutSourceCallCount() int {
	fake.putSourceMutex.RLock()
	defer fake.putSourceMutex.RUnlock()
	return len(fake.putSourceArgsForCall)
}

func (fake *FakeSourceRepoInterface) PutSourceCalls(stub func(context.Context, *api.SourceInput) error) {
	fake.putSourceMutex.Lock()
	defer fake.putSourceMutex.Unlock()
	fake.PutSourceStub = stub
}

func (fake *FakeSourceRepoInterface) PutSourceArgsForCall(i int) (context.Context, *api.SourceInput) {
	fake.putSourceMutex.RLock()
	defer fake.putSourceMutex.RUnlock()
	argsForCall := fake.putSourceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSourceRepoInterface) PutSourceReturns(result1 error) {
	fake.putSourceMutex.Lock()
	defer fake.putSourceMutex.Unlock()
	fake.PutSourceStub = nil
	fake.putSourceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepoInterface) PutSourceReturnsOnCall(i int, result1 error) {
	fake.putSourceMutex.Lock()
	defer fake.putSourceMutex.Unlock()
	fake.PutSourceStub = nil
	if fake.putSourceReturnsOnCall == nil {
		fake.putSourceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.putSourceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepoInterface) UpdateSourceByUriDigest(arg1 context.Context, arg2 *api.SourceInput, arg3 string) error {
	fake.updateSourceByUriDigestMutex.Lock()
	ret, specificReturn := fake.updateSourceByUriDigestReturnsOnCall[len(fake.updateSourceByUriDigestArgsForCall)]
	fake.updateSourceByUriDigestArgsForCall = append(fake.updateSourceByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 *api.SourceInput
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.UpdateSourceByUriDigestStub
	fakeReturns := fake.updateSourceByUriDigestReturns
	fake.recordInvocation("UpdateSourceByUriDigest", []interface{}{arg1, arg2, arg3})
	fake.updateSourceByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSourceRepoInterface) UpdateSourceByUriDigestCallCount() int {
	fake.updateSourceByUriDigestMutex.RLock()
	defer fake.updateSourceByUriDigestMutex.RUnlock()
	return len(fake.updateSourceByUriDigestArgsForCall)
}

func (fake *FakeSourceRepoInterface) UpdateSourceByUriDigestCalls(stub func(context.Context, *api.SourceInput, string) error) {
	fake.updateSourceByUriDigestMutex.Lock()
	defer fake.updateSourceByUriDigestMutex.Unlock()
	fake.UpdateSourceByUriDigestStub = stub
}

func (fake *FakeSourceRepoInterface) UpdateSourceByUriDigestArgsForCall(i int) (context.Context, *api.SourceInput, string) {
	fake.updateSourceByUriDigestMutex.RLock()
	defer fake.updateSourceByUriDigestMutex.RUnlock()
	argsForCall := fake.updateSourceByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSourceRepoInterface) UpdateSourceByUriDigestReturns(result1 error) {
	fake.updateSourceByUriDigestMutex.Lock()
	defer fake.updateSourceByUriDigestMutex.Unlock()
	fake.UpdateSourceByUriDigestStub = nil
	fake.updateSourceByUriDigestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepoInterface) UpdateSourceByUriDigestReturnsOnCall(i int, result1 error) {
	fake.updateSourceByUriDigestMutex.Lock()
	defer fake.updateSourceByUriDigestMutex.Unlock()
	fake.UpdateSourceByUriDigestStub = nil
	if fake.updateSourceByUriDigestReturnsOnCall == nil {
		fake.updateSourceByUriDigestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateSourceByUriDigestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSourceRepoInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSourceRepoInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ source.SourceRepoInterface = new(FakeSourceRepoInterface)
