services:
  database:
    image: postgres:15.17
    restart: always
    shm_size: 256mb
    environment:
    - POSTGRES_USER=sourcescore
    - POSTGRES_PASSWORD=sourcescore
    - POSTGRES_DB=sourcescore
    ports:
    - 5432:5432
    volumes:
    - ./db/pg:/docker-entrypoint-initdb.d
    - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: ../
      dockerfile: Dockerfile
      no_cache: true
    depends_on:
      database:
        condition: service_started
    restart: always
    environment:
    - APP_USER_PASSWORD=sourcescore
    - PG_HOST=database
    - SUPER_USER_PASSWORD=sourcescore
    - API_KEY=test-key
    ports:
    - "8080:8080"
  adminer:
    image: adminer
    restart: always
    ports:
    - 8081:8080
    depends_on:
      database:
        condition: service_started

volumes:
  postgres_data: