services:
  database:
    image: postgres:15.17
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=sourcescore
      - POSTGRES_PASSWORD=sourcescore
      - POSTGRES_DB=sourcescore
    ports:
      - 5432:5432
  app:
    build:
      context: ../
      dockerfile: Dockerfile
      no_cache: true
    depends_on:
      database:
        condition: service_started
    restart: always
    ports:
      - "8080:8080"