version: '3.9'

services:

  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    ports:
      - "8089:8080"
    environment:
      ADMINER_DEFAULT_DB: postgres
      ADMINER_DEFAULT_SERVER: postgres