// Code generated by counterfeiter. DO NOT EDIT.
package claimfakes

import (
	"context"
	"source-score/pkg/api"
	"source-score/pkg/domain/claim"
	"sync"
)

type FakeClaimRepository struct {
	GetClaimsStub        func(context.Context) ([]api.Claim, error)
	getClaimsMutex       sync.RWMutex
	getClaimsArgsForCall []struct {
		arg1 context.Context
	}
	getClaimsReturns struct {
		result1 []api.Claim
		result2 error
	}
	getClaimsReturnsOnCall map[int]struct {
		result1 []api.Claim
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClaimRepository) GetClaims(arg1 context.Context) ([]api.Claim, error) {
	fake.getClaimsMutex.Lock()
	ret, specificReturn := fake.getClaimsReturnsOnCall[len(fake.getClaimsArgsForCall)]
	fake.getClaimsArgsForCall = append(fake.getClaimsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetClaimsStub
	fakeReturns := fake.getClaimsReturns
	fake.recordInvocation("GetClaims", []interface{}{arg1})
	fake.getClaimsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClaimRepository) GetClaimsCallCount() int {
	fake.getClaimsMutex.RLock()
	defer fake.getClaimsMutex.RUnlock()
	return len(fake.getClaimsArgsForCall)
}

func (fake *FakeClaimRepository) GetClaimsCalls(stub func(context.Context) ([]api.Claim, error)) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = stub
}

func (fake *FakeClaimRepository) GetClaimsArgsForCall(i int) context.Context {
	fake.getClaimsMutex.RLock()
	defer fake.getClaimsMutex.RUnlock()
	argsForCall := fake.getClaimsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClaimRepository) GetClaimsReturns(result1 []api.Claim, result2 error) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = nil
	fake.getClaimsReturns = struct {
		result1 []api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimRepository) GetClaimsReturnsOnCall(i int, result1 []api.Claim, result2 error) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = nil
	if fake.getClaimsReturnsOnCall == nil {
		fake.getClaimsReturnsOnCall = make(map[int]struct {
			result1 []api.Claim
			result2 error
		})
	}
	fake.getClaimsReturnsOnCall[i] = struct {
		result1 []api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClaimRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ claim.ClaimRepository = new(FakeClaimRepository)
