// Code generated by counterfeiter. DO NOT EDIT.
package claimfakes

import (
	"context"
	"source-score/pkg/api"
	"source-score/pkg/domain/claim"
	"sync"
)

type FakeClaimRepository struct {
	DeleteClaimByUriDigestStub        func(context.Context, *api.Claim) error
	deleteClaimByUriDigestMutex       sync.RWMutex
	deleteClaimByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 *api.Claim
	}
	deleteClaimByUriDigestReturns struct {
		result1 error
	}
	deleteClaimByUriDigestReturnsOnCall map[int]struct {
		result1 error
	}
	GetClaimByUriDigestStub        func(context.Context, string) (*api.Claim, error)
	getClaimByUriDigestMutex       sync.RWMutex
	getClaimByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getClaimByUriDigestReturns struct {
		result1 *api.Claim
		result2 error
	}
	getClaimByUriDigestReturnsOnCall map[int]struct {
		result1 *api.Claim
		result2 error
	}
	GetClaimsStub        func(context.Context) ([]api.Claim, error)
	getClaimsMutex       sync.RWMutex
	getClaimsArgsForCall []struct {
		arg1 context.Context
	}
	getClaimsReturns struct {
		result1 []api.Claim
		result2 error
	}
	getClaimsReturnsOnCall map[int]struct {
		result1 []api.Claim
		result2 error
	}
	PostClaimStub        func(context.Context, *api.ClaimInput) (string, error)
	postClaimMutex       sync.RWMutex
	postClaimArgsForCall []struct {
		arg1 context.Context
		arg2 *api.ClaimInput
	}
	postClaimReturns struct {
		result1 string
		result2 error
	}
	postClaimReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClaimRepository) DeleteClaimByUriDigest(arg1 context.Context, arg2 *api.Claim) error {
	fake.deleteClaimByUriDigestMutex.Lock()
	ret, specificReturn := fake.deleteClaimByUriDigestReturnsOnCall[len(fake.deleteClaimByUriDigestArgsForCall)]
	fake.deleteClaimByUriDigestArgsForCall = append(fake.deleteClaimByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 *api.Claim
	}{arg1, arg2})
	stub := fake.DeleteClaimByUriDigestStub
	fakeReturns := fake.deleteClaimByUriDigestReturns
	fake.recordInvocation("DeleteClaimByUriDigest", []interface{}{arg1, arg2})
	fake.deleteClaimByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClaimRepository) DeleteClaimByUriDigestCallCount() int {
	fake.deleteClaimByUriDigestMutex.RLock()
	defer fake.deleteClaimByUriDigestMutex.RUnlock()
	return len(fake.deleteClaimByUriDigestArgsForCall)
}

func (fake *FakeClaimRepository) DeleteClaimByUriDigestCalls(stub func(context.Context, *api.Claim) error) {
	fake.deleteClaimByUriDigestMutex.Lock()
	defer fake.deleteClaimByUriDigestMutex.Unlock()
	fake.DeleteClaimByUriDigestStub = stub
}

func (fake *FakeClaimRepository) DeleteClaimByUriDigestArgsForCall(i int) (context.Context, *api.Claim) {
	fake.deleteClaimByUriDigestMutex.RLock()
	defer fake.deleteClaimByUriDigestMutex.RUnlock()
	argsForCall := fake.deleteClaimByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClaimRepository) DeleteClaimByUriDigestReturns(result1 error) {
	fake.deleteClaimByUriDigestMutex.Lock()
	defer fake.deleteClaimByUriDigestMutex.Unlock()
	fake.DeleteClaimByUriDigestStub = nil
	fake.deleteClaimByUriDigestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClaimRepository) DeleteClaimByUriDigestReturnsOnCall(i int, result1 error) {
	fake.deleteClaimByUriDigestMutex.Lock()
	defer fake.deleteClaimByUriDigestMutex.Unlock()
	fake.DeleteClaimByUriDigestStub = nil
	if fake.deleteClaimByUriDigestReturnsOnCall == nil {
		fake.deleteClaimByUriDigestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteClaimByUriDigestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClaimRepository) GetClaimByUriDigest(arg1 context.Context, arg2 string) (*api.Claim, error) {
	fake.getClaimByUriDigestMutex.Lock()
	ret, specificReturn := fake.getClaimByUriDigestReturnsOnCall[len(fake.getClaimByUriDigestArgsForCall)]
	fake.getClaimByUriDigestArgsForCall = append(fake.getClaimByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetClaimByUriDigestStub
	fakeReturns := fake.getClaimByUriDigestReturns
	fake.recordInvocation("GetClaimByUriDigest", []interface{}{arg1, arg2})
	fake.getClaimByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClaimRepository) GetClaimByUriDigestCallCount() int {
	fake.getClaimByUriDigestMutex.RLock()
	defer fake.getClaimByUriDigestMutex.RUnlock()
	return len(fake.getClaimByUriDigestArgsForCall)
}

func (fake *FakeClaimRepository) GetClaimByUriDigestCalls(stub func(context.Context, string) (*api.Claim, error)) {
	fake.getClaimByUriDigestMutex.Lock()
	defer fake.getClaimByUriDigestMutex.Unlock()
	fake.GetClaimByUriDigestStub = stub
}

func (fake *FakeClaimRepository) GetClaimByUriDigestArgsForCall(i int) (context.Context, string) {
	fake.getClaimByUriDigestMutex.RLock()
	defer fake.getClaimByUriDigestMutex.RUnlock()
	argsForCall := fake.getClaimByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClaimRepository) GetClaimByUriDigestReturns(result1 *api.Claim, result2 error) {
	fake.getClaimByUriDigestMutex.Lock()
	defer fake.getClaimByUriDigestMutex.Unlock()
	fake.GetClaimByUriDigestStub = nil
	fake.getClaimByUriDigestReturns = struct {
		result1 *api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimRepository) GetClaimByUriDigestReturnsOnCall(i int, result1 *api.Claim, result2 error) {
	fake.getClaimByUriDigestMutex.Lock()
	defer fake.getClaimByUriDigestMutex.Unlock()
	fake.GetClaimByUriDigestStub = nil
	if fake.getClaimByUriDigestReturnsOnCall == nil {
		fake.getClaimByUriDigestReturnsOnCall = make(map[int]struct {
			result1 *api.Claim
			result2 error
		})
	}
	fake.getClaimByUriDigestReturnsOnCall[i] = struct {
		result1 *api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimRepository) GetClaims(arg1 context.Context) ([]api.Claim, error) {
	fake.getClaimsMutex.Lock()
	ret, specificReturn := fake.getClaimsReturnsOnCall[len(fake.getClaimsArgsForCall)]
	fake.getClaimsArgsForCall = append(fake.getClaimsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetClaimsStub
	fakeReturns := fake.getClaimsReturns
	fake.recordInvocation("GetClaims", []interface{}{arg1})
	fake.getClaimsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClaimRepository) GetClaimsCallCount() int {
	fake.getClaimsMutex.RLock()
	defer fake.getClaimsMutex.RUnlock()
	return len(fake.getClaimsArgsForCall)
}

func (fake *FakeClaimRepository) GetClaimsCalls(stub func(context.Context) ([]api.Claim, error)) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = stub
}

func (fake *FakeClaimRepository) GetClaimsArgsForCall(i int) context.Context {
	fake.getClaimsMutex.RLock()
	defer fake.getClaimsMutex.RUnlock()
	argsForCall := fake.getClaimsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClaimRepository) GetClaimsReturns(result1 []api.Claim, result2 error) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = nil
	fake.getClaimsReturns = struct {
		result1 []api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimRepository) GetClaimsReturnsOnCall(i int, result1 []api.Claim, result2 error) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = nil
	if fake.getClaimsReturnsOnCall == nil {
		fake.getClaimsReturnsOnCall = make(map[int]struct {
			result1 []api.Claim
			result2 error
		})
	}
	fake.getClaimsReturnsOnCall[i] = struct {
		result1 []api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimRepository) PostClaim(arg1 context.Context, arg2 *api.ClaimInput) (string, error) {
	fake.postClaimMutex.Lock()
	ret, specificReturn := fake.postClaimReturnsOnCall[len(fake.postClaimArgsForCall)]
	fake.postClaimArgsForCall = append(fake.postClaimArgsForCall, struct {
		arg1 context.Context
		arg2 *api.ClaimInput
	}{arg1, arg2})
	stub := fake.PostClaimStub
	fakeReturns := fake.postClaimReturns
	fake.recordInvocation("PostClaim", []interface{}{arg1, arg2})
	fake.postClaimMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClaimRepository) PostClaimCallCount() int {
	fake.postClaimMutex.RLock()
	defer fake.postClaimMutex.RUnlock()
	return len(fake.postClaimArgsForCall)
}

func (fake *FakeClaimRepository) PostClaimCalls(stub func(context.Context, *api.ClaimInput) (string, error)) {
	fake.postClaimMutex.Lock()
	defer fake.postClaimMutex.Unlock()
	fake.PostClaimStub = stub
}

func (fake *FakeClaimRepository) PostClaimArgsForCall(i int) (context.Context, *api.ClaimInput) {
	fake.postClaimMutex.RLock()
	defer fake.postClaimMutex.RUnlock()
	argsForCall := fake.postClaimArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClaimRepository) PostClaimReturns(result1 string, result2 error) {
	fake.postClaimMutex.Lock()
	defer fake.postClaimMutex.Unlock()
	fake.PostClaimStub = nil
	fake.postClaimReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimRepository) PostClaimReturnsOnCall(i int, result1 string, result2 error) {
	fake.postClaimMutex.Lock()
	defer fake.postClaimMutex.Unlock()
	fake.PostClaimStub = nil
	if fake.postClaimReturnsOnCall == nil {
		fake.postClaimReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.postClaimReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClaimRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ claim.ClaimRepository = new(FakeClaimRepository)
