// Code generated by counterfeiter. DO NOT EDIT.
package claimfakes

import (
	"context"
	"source-score/pkg/api"
	"source-score/pkg/domain/claim"
	"sync"
)

type FakeClaimService struct {
	GetClaimsStub        func(context.Context) ([]api.Claim, error)
	getClaimsMutex       sync.RWMutex
	getClaimsArgsForCall []struct {
		arg1 context.Context
	}
	getClaimsReturns struct {
		result1 []api.Claim
		result2 error
	}
	getClaimsReturnsOnCall map[int]struct {
		result1 []api.Claim
		result2 error
	}
	PostClaimStub        func(context.Context, *api.ClaimInput) (string, error)
	postClaimMutex       sync.RWMutex
	postClaimArgsForCall []struct {
		arg1 context.Context
		arg2 *api.ClaimInput
	}
	postClaimReturns struct {
		result1 string
		result2 error
	}
	postClaimReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClaimService) GetClaims(arg1 context.Context) ([]api.Claim, error) {
	fake.getClaimsMutex.Lock()
	ret, specificReturn := fake.getClaimsReturnsOnCall[len(fake.getClaimsArgsForCall)]
	fake.getClaimsArgsForCall = append(fake.getClaimsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetClaimsStub
	fakeReturns := fake.getClaimsReturns
	fake.recordInvocation("GetClaims", []interface{}{arg1})
	fake.getClaimsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClaimService) GetClaimsCallCount() int {
	fake.getClaimsMutex.RLock()
	defer fake.getClaimsMutex.RUnlock()
	return len(fake.getClaimsArgsForCall)
}

func (fake *FakeClaimService) GetClaimsCalls(stub func(context.Context) ([]api.Claim, error)) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = stub
}

func (fake *FakeClaimService) GetClaimsArgsForCall(i int) context.Context {
	fake.getClaimsMutex.RLock()
	defer fake.getClaimsMutex.RUnlock()
	argsForCall := fake.getClaimsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClaimService) GetClaimsReturns(result1 []api.Claim, result2 error) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = nil
	fake.getClaimsReturns = struct {
		result1 []api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimService) GetClaimsReturnsOnCall(i int, result1 []api.Claim, result2 error) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = nil
	if fake.getClaimsReturnsOnCall == nil {
		fake.getClaimsReturnsOnCall = make(map[int]struct {
			result1 []api.Claim
			result2 error
		})
	}
	fake.getClaimsReturnsOnCall[i] = struct {
		result1 []api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimService) PostClaim(arg1 context.Context, arg2 *api.ClaimInput) (string, error) {
	fake.postClaimMutex.Lock()
	ret, specificReturn := fake.postClaimReturnsOnCall[len(fake.postClaimArgsForCall)]
	fake.postClaimArgsForCall = append(fake.postClaimArgsForCall, struct {
		arg1 context.Context
		arg2 *api.ClaimInput
	}{arg1, arg2})
	stub := fake.PostClaimStub
	fakeReturns := fake.postClaimReturns
	fake.recordInvocation("PostClaim", []interface{}{arg1, arg2})
	fake.postClaimMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClaimService) PostClaimCallCount() int {
	fake.postClaimMutex.RLock()
	defer fake.postClaimMutex.RUnlock()
	return len(fake.postClaimArgsForCall)
}

func (fake *FakeClaimService) PostClaimCalls(stub func(context.Context, *api.ClaimInput) (string, error)) {
	fake.postClaimMutex.Lock()
	defer fake.postClaimMutex.Unlock()
	fake.PostClaimStub = stub
}

func (fake *FakeClaimService) PostClaimArgsForCall(i int) (context.Context, *api.ClaimInput) {
	fake.postClaimMutex.RLock()
	defer fake.postClaimMutex.RUnlock()
	argsForCall := fake.postClaimArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClaimService) PostClaimReturns(result1 string, result2 error) {
	fake.postClaimMutex.Lock()
	defer fake.postClaimMutex.Unlock()
	fake.PostClaimStub = nil
	fake.postClaimReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimService) PostClaimReturnsOnCall(i int, result1 string, result2 error) {
	fake.postClaimMutex.Lock()
	defer fake.postClaimMutex.Unlock()
	fake.PostClaimStub = nil
	if fake.postClaimReturnsOnCall == nil {
		fake.postClaimReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.postClaimReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClaimService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ claim.ClaimService = new(FakeClaimService)
