// Code generated by counterfeiter. DO NOT EDIT.
package claimfakes

import (
	"context"
	"source-score/pkg/api"
	"source-score/pkg/domain/claim"
	"sync"
)

type FakeClaimService struct {
	DeleteClaimByUriDigestStub        func(context.Context, string) error
	deleteClaimByUriDigestMutex       sync.RWMutex
	deleteClaimByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	deleteClaimByUriDigestReturns struct {
		result1 error
	}
	deleteClaimByUriDigestReturnsOnCall map[int]struct {
		result1 error
	}
	GetClaimByUriDigestStub        func(context.Context, string) (*api.Claim, error)
	getClaimByUriDigestMutex       sync.RWMutex
	getClaimByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getClaimByUriDigestReturns struct {
		result1 *api.Claim
		result2 error
	}
	getClaimByUriDigestReturnsOnCall map[int]struct {
		result1 *api.Claim
		result2 error
	}
	GetClaimsStub        func(context.Context) ([]api.Claim, error)
	getClaimsMutex       sync.RWMutex
	getClaimsArgsForCall []struct {
		arg1 context.Context
	}
	getClaimsReturns struct {
		result1 []api.Claim
		result2 error
	}
	getClaimsReturnsOnCall map[int]struct {
		result1 []api.Claim
		result2 error
	}
	PatchClaimByUriDigestStub        func(context.Context, *api.ClaimPatchInput, string) error
	patchClaimByUriDigestMutex       sync.RWMutex
	patchClaimByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 *api.ClaimPatchInput
		arg3 string
	}
	patchClaimByUriDigestReturns struct {
		result1 error
	}
	patchClaimByUriDigestReturnsOnCall map[int]struct {
		result1 error
	}
	PostClaimStub        func(context.Context, *api.ClaimInput) (string, error)
	postClaimMutex       sync.RWMutex
	postClaimArgsForCall []struct {
		arg1 context.Context
		arg2 *api.ClaimInput
	}
	postClaimReturns struct {
		result1 string
		result2 error
	}
	postClaimReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	VerifyAllClaimsStub        func(context.Context) error
	verifyAllClaimsMutex       sync.RWMutex
	verifyAllClaimsArgsForCall []struct {
		arg1 context.Context
	}
	verifyAllClaimsReturns struct {
		result1 error
	}
	verifyAllClaimsReturnsOnCall map[int]struct {
		result1 error
	}
	VerifyClaimByUriDigestStub        func(context.Context, *api.ClaimVerification, string) error
	verifyClaimByUriDigestMutex       sync.RWMutex
	verifyClaimByUriDigestArgsForCall []struct {
		arg1 context.Context
		arg2 *api.ClaimVerification
		arg3 string
	}
	verifyClaimByUriDigestReturns struct {
		result1 error
	}
	verifyClaimByUriDigestReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClaimService) DeleteClaimByUriDigest(arg1 context.Context, arg2 string) error {
	fake.deleteClaimByUriDigestMutex.Lock()
	ret, specificReturn := fake.deleteClaimByUriDigestReturnsOnCall[len(fake.deleteClaimByUriDigestArgsForCall)]
	fake.deleteClaimByUriDigestArgsForCall = append(fake.deleteClaimByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DeleteClaimByUriDigestStub
	fakeReturns := fake.deleteClaimByUriDigestReturns
	fake.recordInvocation("DeleteClaimByUriDigest", []interface{}{arg1, arg2})
	fake.deleteClaimByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClaimService) DeleteClaimByUriDigestCallCount() int {
	fake.deleteClaimByUriDigestMutex.RLock()
	defer fake.deleteClaimByUriDigestMutex.RUnlock()
	return len(fake.deleteClaimByUriDigestArgsForCall)
}

func (fake *FakeClaimService) DeleteClaimByUriDigestCalls(stub func(context.Context, string) error) {
	fake.deleteClaimByUriDigestMutex.Lock()
	defer fake.deleteClaimByUriDigestMutex.Unlock()
	fake.DeleteClaimByUriDigestStub = stub
}

func (fake *FakeClaimService) DeleteClaimByUriDigestArgsForCall(i int) (context.Context, string) {
	fake.deleteClaimByUriDigestMutex.RLock()
	defer fake.deleteClaimByUriDigestMutex.RUnlock()
	argsForCall := fake.deleteClaimByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClaimService) DeleteClaimByUriDigestReturns(result1 error) {
	fake.deleteClaimByUriDigestMutex.Lock()
	defer fake.deleteClaimByUriDigestMutex.Unlock()
	fake.DeleteClaimByUriDigestStub = nil
	fake.deleteClaimByUriDigestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClaimService) DeleteClaimByUriDigestReturnsOnCall(i int, result1 error) {
	fake.deleteClaimByUriDigestMutex.Lock()
	defer fake.deleteClaimByUriDigestMutex.Unlock()
	fake.DeleteClaimByUriDigestStub = nil
	if fake.deleteClaimByUriDigestReturnsOnCall == nil {
		fake.deleteClaimByUriDigestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteClaimByUriDigestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClaimService) GetClaimByUriDigest(arg1 context.Context, arg2 string) (*api.Claim, error) {
	fake.getClaimByUriDigestMutex.Lock()
	ret, specificReturn := fake.getClaimByUriDigestReturnsOnCall[len(fake.getClaimByUriDigestArgsForCall)]
	fake.getClaimByUriDigestArgsForCall = append(fake.getClaimByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetClaimByUriDigestStub
	fakeReturns := fake.getClaimByUriDigestReturns
	fake.recordInvocation("GetClaimByUriDigest", []interface{}{arg1, arg2})
	fake.getClaimByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClaimService) GetClaimByUriDigestCallCount() int {
	fake.getClaimByUriDigestMutex.RLock()
	defer fake.getClaimByUriDigestMutex.RUnlock()
	return len(fake.getClaimByUriDigestArgsForCall)
}

func (fake *FakeClaimService) GetClaimByUriDigestCalls(stub func(context.Context, string) (*api.Claim, error)) {
	fake.getClaimByUriDigestMutex.Lock()
	defer fake.getClaimByUriDigestMutex.Unlock()
	fake.GetClaimByUriDigestStub = stub
}

func (fake *FakeClaimService) GetClaimByUriDigestArgsForCall(i int) (context.Context, string) {
	fake.getClaimByUriDigestMutex.RLock()
	defer fake.getClaimByUriDigestMutex.RUnlock()
	argsForCall := fake.getClaimByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClaimService) GetClaimByUriDigestReturns(result1 *api.Claim, result2 error) {
	fake.getClaimByUriDigestMutex.Lock()
	defer fake.getClaimByUriDigestMutex.Unlock()
	fake.GetClaimByUriDigestStub = nil
	fake.getClaimByUriDigestReturns = struct {
		result1 *api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimService) GetClaimByUriDigestReturnsOnCall(i int, result1 *api.Claim, result2 error) {
	fake.getClaimByUriDigestMutex.Lock()
	defer fake.getClaimByUriDigestMutex.Unlock()
	fake.GetClaimByUriDigestStub = nil
	if fake.getClaimByUriDigestReturnsOnCall == nil {
		fake.getClaimByUriDigestReturnsOnCall = make(map[int]struct {
			result1 *api.Claim
			result2 error
		})
	}
	fake.getClaimByUriDigestReturnsOnCall[i] = struct {
		result1 *api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimService) GetClaims(arg1 context.Context) ([]api.Claim, error) {
	fake.getClaimsMutex.Lock()
	ret, specificReturn := fake.getClaimsReturnsOnCall[len(fake.getClaimsArgsForCall)]
	fake.getClaimsArgsForCall = append(fake.getClaimsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetClaimsStub
	fakeReturns := fake.getClaimsReturns
	fake.recordInvocation("GetClaims", []interface{}{arg1})
	fake.getClaimsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClaimService) GetClaimsCallCount() int {
	fake.getClaimsMutex.RLock()
	defer fake.getClaimsMutex.RUnlock()
	return len(fake.getClaimsArgsForCall)
}

func (fake *FakeClaimService) GetClaimsCalls(stub func(context.Context) ([]api.Claim, error)) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = stub
}

func (fake *FakeClaimService) GetClaimsArgsForCall(i int) context.Context {
	fake.getClaimsMutex.RLock()
	defer fake.getClaimsMutex.RUnlock()
	argsForCall := fake.getClaimsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClaimService) GetClaimsReturns(result1 []api.Claim, result2 error) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = nil
	fake.getClaimsReturns = struct {
		result1 []api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimService) GetClaimsReturnsOnCall(i int, result1 []api.Claim, result2 error) {
	fake.getClaimsMutex.Lock()
	defer fake.getClaimsMutex.Unlock()
	fake.GetClaimsStub = nil
	if fake.getClaimsReturnsOnCall == nil {
		fake.getClaimsReturnsOnCall = make(map[int]struct {
			result1 []api.Claim
			result2 error
		})
	}
	fake.getClaimsReturnsOnCall[i] = struct {
		result1 []api.Claim
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimService) PatchClaimByUriDigest(arg1 context.Context, arg2 *api.ClaimPatchInput, arg3 string) error {
	fake.patchClaimByUriDigestMutex.Lock()
	ret, specificReturn := fake.patchClaimByUriDigestReturnsOnCall[len(fake.patchClaimByUriDigestArgsForCall)]
	fake.patchClaimByUriDigestArgsForCall = append(fake.patchClaimByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 *api.ClaimPatchInput
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.PatchClaimByUriDigestStub
	fakeReturns := fake.patchClaimByUriDigestReturns
	fake.recordInvocation("PatchClaimByUriDigest", []interface{}{arg1, arg2, arg3})
	fake.patchClaimByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClaimService) PatchClaimByUriDigestCallCount() int {
	fake.patchClaimByUriDigestMutex.RLock()
	defer fake.patchClaimByUriDigestMutex.RUnlock()
	return len(fake.patchClaimByUriDigestArgsForCall)
}

func (fake *FakeClaimService) PatchClaimByUriDigestCalls(stub func(context.Context, *api.ClaimPatchInput, string) error) {
	fake.patchClaimByUriDigestMutex.Lock()
	defer fake.patchClaimByUriDigestMutex.Unlock()
	fake.PatchClaimByUriDigestStub = stub
}

func (fake *FakeClaimService) PatchClaimByUriDigestArgsForCall(i int) (context.Context, *api.ClaimPatchInput, string) {
	fake.patchClaimByUriDigestMutex.RLock()
	defer fake.patchClaimByUriDigestMutex.RUnlock()
	argsForCall := fake.patchClaimByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClaimService) PatchClaimByUriDigestReturns(result1 error) {
	fake.patchClaimByUriDigestMutex.Lock()
	defer fake.patchClaimByUriDigestMutex.Unlock()
	fake.PatchClaimByUriDigestStub = nil
	fake.patchClaimByUriDigestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClaimService) PatchClaimByUriDigestReturnsOnCall(i int, result1 error) {
	fake.patchClaimByUriDigestMutex.Lock()
	defer fake.patchClaimByUriDigestMutex.Unlock()
	fake.PatchClaimByUriDigestStub = nil
	if fake.patchClaimByUriDigestReturnsOnCall == nil {
		fake.patchClaimByUriDigestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.patchClaimByUriDigestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClaimService) PostClaim(arg1 context.Context, arg2 *api.ClaimInput) (string, error) {
	fake.postClaimMutex.Lock()
	ret, specificReturn := fake.postClaimReturnsOnCall[len(fake.postClaimArgsForCall)]
	fake.postClaimArgsForCall = append(fake.postClaimArgsForCall, struct {
		arg1 context.Context
		arg2 *api.ClaimInput
	}{arg1, arg2})
	stub := fake.PostClaimStub
	fakeReturns := fake.postClaimReturns
	fake.recordInvocation("PostClaim", []interface{}{arg1, arg2})
	fake.postClaimMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClaimService) PostClaimCallCount() int {
	fake.postClaimMutex.RLock()
	defer fake.postClaimMutex.RUnlock()
	return len(fake.postClaimArgsForCall)
}

func (fake *FakeClaimService) PostClaimCalls(stub func(context.Context, *api.ClaimInput) (string, error)) {
	fake.postClaimMutex.Lock()
	defer fake.postClaimMutex.Unlock()
	fake.PostClaimStub = stub
}

func (fake *FakeClaimService) PostClaimArgsForCall(i int) (context.Context, *api.ClaimInput) {
	fake.postClaimMutex.RLock()
	defer fake.postClaimMutex.RUnlock()
	argsForCall := fake.postClaimArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClaimService) PostClaimReturns(result1 string, result2 error) {
	fake.postClaimMutex.Lock()
	defer fake.postClaimMutex.Unlock()
	fake.PostClaimStub = nil
	fake.postClaimReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimService) PostClaimReturnsOnCall(i int, result1 string, result2 error) {
	fake.postClaimMutex.Lock()
	defer fake.postClaimMutex.Unlock()
	fake.PostClaimStub = nil
	if fake.postClaimReturnsOnCall == nil {
		fake.postClaimReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.postClaimReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClaimService) VerifyAllClaims(arg1 context.Context) error {
	fake.verifyAllClaimsMutex.Lock()
	ret, specificReturn := fake.verifyAllClaimsReturnsOnCall[len(fake.verifyAllClaimsArgsForCall)]
	fake.verifyAllClaimsArgsForCall = append(fake.verifyAllClaimsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.VerifyAllClaimsStub
	fakeReturns := fake.verifyAllClaimsReturns
	fake.recordInvocation("VerifyAllClaims", []interface{}{arg1})
	fake.verifyAllClaimsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClaimService) VerifyAllClaimsCallCount() int {
	fake.verifyAllClaimsMutex.RLock()
	defer fake.verifyAllClaimsMutex.RUnlock()
	return len(fake.verifyAllClaimsArgsForCall)
}

func (fake *FakeClaimService) VerifyAllClaimsCalls(stub func(context.Context) error) {
	fake.verifyAllClaimsMutex.Lock()
	defer fake.verifyAllClaimsMutex.Unlock()
	fake.VerifyAllClaimsStub = stub
}

func (fake *FakeClaimService) VerifyAllClaimsArgsForCall(i int) context.Context {
	fake.verifyAllClaimsMutex.RLock()
	defer fake.verifyAllClaimsMutex.RUnlock()
	argsForCall := fake.verifyAllClaimsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClaimService) VerifyAllClaimsReturns(result1 error) {
	fake.verifyAllClaimsMutex.Lock()
	defer fake.verifyAllClaimsMutex.Unlock()
	fake.VerifyAllClaimsStub = nil
	fake.verifyAllClaimsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClaimService) VerifyAllClaimsReturnsOnCall(i int, result1 error) {
	fake.verifyAllClaimsMutex.Lock()
	defer fake.verifyAllClaimsMutex.Unlock()
	fake.VerifyAllClaimsStub = nil
	if fake.verifyAllClaimsReturnsOnCall == nil {
		fake.verifyAllClaimsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyAllClaimsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClaimService) VerifyClaimByUriDigest(arg1 context.Context, arg2 *api.ClaimVerification, arg3 string) error {
	fake.verifyClaimByUriDigestMutex.Lock()
	ret, specificReturn := fake.verifyClaimByUriDigestReturnsOnCall[len(fake.verifyClaimByUriDigestArgsForCall)]
	fake.verifyClaimByUriDigestArgsForCall = append(fake.verifyClaimByUriDigestArgsForCall, struct {
		arg1 context.Context
		arg2 *api.ClaimVerification
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.VerifyClaimByUriDigestStub
	fakeReturns := fake.verifyClaimByUriDigestReturns
	fake.recordInvocation("VerifyClaimByUriDigest", []interface{}{arg1, arg2, arg3})
	fake.verifyClaimByUriDigestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClaimService) VerifyClaimByUriDigestCallCount() int {
	fake.verifyClaimByUriDigestMutex.RLock()
	defer fake.verifyClaimByUriDigestMutex.RUnlock()
	return len(fake.verifyClaimByUriDigestArgsForCall)
}

func (fake *FakeClaimService) VerifyClaimByUriDigestCalls(stub func(context.Context, *api.ClaimVerification, string) error) {
	fake.verifyClaimByUriDigestMutex.Lock()
	defer fake.verifyClaimByUriDigestMutex.Unlock()
	fake.VerifyClaimByUriDigestStub = stub
}

func (fake *FakeClaimService) VerifyClaimByUriDigestArgsForCall(i int) (context.Context, *api.ClaimVerification, string) {
	fake.verifyClaimByUriDigestMutex.RLock()
	defer fake.verifyClaimByUriDigestMutex.RUnlock()
	argsForCall := fake.verifyClaimByUriDigestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClaimService) VerifyClaimByUriDigestReturns(result1 error) {
	fake.verifyClaimByUriDigestMutex.Lock()
	defer fake.verifyClaimByUriDigestMutex.Unlock()
	fake.VerifyClaimByUriDigestStub = nil
	fake.verifyClaimByUriDigestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClaimService) VerifyClaimByUriDigestReturnsOnCall(i int, result1 error) {
	fake.verifyClaimByUriDigestMutex.Lock()
	defer fake.verifyClaimByUriDigestMutex.Unlock()
	fake.VerifyClaimByUriDigestStub = nil
	if fake.verifyClaimByUriDigestReturnsOnCall == nil {
		fake.verifyClaimByUriDigestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyClaimByUriDigestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClaimService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClaimService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ claim.ClaimService = new(FakeClaimService)
