openapi: "3.0.0"
info:
  version: 0.0.1
  title: Minimal ping API server
paths:
  /ping:
    get:
      responses:
        '200':
          description: pong response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
components:
  schemas:
    # base types
    Pong:
      type: object
      required:
        - pong
      properties:
        pong:
          type: string
          example: pong