openapi: 3.0.0
info:
  title: Source Score Microservice
  description: An application to rate sources based on the validity of their claims
  version: 0.0.1

paths:
  /ping:
    get:
      responses:
        200:
          description: pong response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'

  /api/v1/sources:
    get:
      tags:
      - sources
      operationId: getSources
      responses:
        200:
          description: source returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Source'

  /api/v1/source:
    post:
      tags:
      - source
      operationId: createSource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SourceInput'
      responses:
        201:
          description: source created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSourceResponse'

  /api/v1/source/{uriDigest}:
    get:
      tags:
      - source
      operationId: getSource
      parameters:
      - in: path
        name: uriDigest
        required: true
        schema:
          type: string
      responses:
        200:
          description: source returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'

    patch:
      tags:
        - source
      operationId: patchSource
      parameters:
      - in: path
        name: uriDigest
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SourcePatchInput'
      responses:
        204:
          description: source updated

    delete:
      tags:
      - source
      operationId: deleteSource
      parameters:
      - in: path
        name: uriDigest
        required: true
        schema:
          type: string
      responses:
        204:
          description: source deleted

components:
  schemas:
    Pong:
      type: object
      required:
      - pong
      properties:
        pong:
          type: string
          example: pong

    SourceInput:
      type: object
      required:
      - name
      - summary
      - tags
      - uri
      properties:
        name:
          type: string
          x-oapi-codegen-extra-tags:
            validate: nonempty
            binding: required
        summary:
          type: string
          x-oapi-codegen-extra-tags:
            validate: nonempty
            binding: required
        tags:
          type: string
          x-oapi-codegen-extra-tags:
            validate: nonempty,nospace
            binding: required
        uri:
          type: string
          x-oapi-codegen-extra-tags:
            validate: nonempty,httpsurl
            binding: required

    SourcePatchInput:
      type: object
      properties:
        name:
          type: string
          x-oapi-codegen-extra-tags:
            validate: nonempty,omitnil
        summary:
          type: string
          x-oapi-codegen-extra-tags:
            validate: nonempty,omitnil
        tags:
          type: string
          x-oapi-codegen-extra-tags:
            validate: nonempty,nospace,omitnil
        uri:
          type: string
          x-oapi-codegen-extra-tags:
            validate: nonempty,httpsurl,omitnil

    Source:
      type: object
      required:
      - name
      - score
      - summary
      - tags
      - uri
      - uriDigest
      properties:
        name:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        score:
          type: number
          format: double
          x-oapi-codegen-extra-tags:
            binding: required
        uriDigest:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
            gorm: primaryKey
        summary:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        tags:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        uri:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required

    CreateSourceResponse:
      type: object
      required:
      - uriDigest
      properties:
        uriDigest:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required