openapi: 3.0.0
info:
  title: Source Score Microservice
  description: An application to rate sources based on the validity of their claims
  version: 0.0.1

paths:
  /ping:
    get:
      responses:
        200:
          description: pong response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'

  /api/v1/sources:
    post:
      tags:
        - source
      operationId: createSource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSource'
      responses:
        201:
          description: source created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'

  /api/v1/sources/{uriDigest}:
    get:
      tags:
        - source
      operationId: getSource
      parameters:
        - in: path
          name: uriDigest
          required: true
          schema:
            type: string
      responses:
        200:
          description: source retrned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'

    put:
      tags:
        - source
      operationId: updateSource
      parameters:
        - in: path
          name: uriDigest
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSource'
      responses:
        200:
          description: source updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'

    delete:
      tags:
        - source
      operationId: deleteSource
      parameters:
        - in: path
          name: uriDigest
          required: true
          schema:
            type: string
      responses:
        204:
          description: source deleted

components:
  schemas:
    Pong:
      type: object
      required:
        - pong
      properties:
        pong:
          type: string
          example: pong

    CreateSource:
      type: object
      required:
        - name
        - summary
        - tags
        - uri
      properties:
        name:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        summary:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        tags:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        uri:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required

    Source:
      type: object
      required:
        - name
        - score
        - summary
        - tags
        - uri
      properties:
        name:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        score:
          type: integer
          format: double
          x-oapi-codegen-extra-tags:
            binding: required
        uriDigest:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
            gorm: primaryKey
        summary:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        tags:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        uri:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required