openapi: 3.0.0
info:
  title: Source Score Microservice
  description: An application to rate sources based on the validity of their claims
  version: 0.0.1

paths:
  /ping:
    get:
      responses:
        200:
          description: pong response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'

  /api/v1/sources:
    get:
      tags:
      - sources
      operationId: getSources
      responses:
        200:
          description: source returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Source'

  /api/v1/source:
    post:
      tags:
      - source
      operationId: createSource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SourceInput'
      responses:
        201:
          description: source created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSourceResponse'

  /api/v1/source/{uriDigest}:
    get:
      tags:
      - source
      operationId: getSource
      parameters:
      - in: path
        name: uriDigest
        required: true
        schema:
          type: string
      responses:
        200:
          description: source returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
        404:
          description: source not found

    patch:
      tags:
        - source
      operationId: patchSource
      parameters:
      - in: path
        name: uriDigest
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SourcePatchInput'
      responses:
        204:
          description: source updated
        404:
          description: source not found

    delete:
      tags:
      - source
      operationId: deleteSource
      parameters:
      - in: path
        name: uriDigest
        required: true
        schema:
          type: string
      responses:
        204:
          description: source deleted
        404:
          description: source not found

  # claim paths
  /api/v1/claims:
    get:
      tags:
      - claims
      operationId: getClaims
      responses:
        200:
          description: returns all claims
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Claim'

  /api/v1/claim:
    post:
      tags:
      - claim
      operationId: postClaim
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimInput'
      responses:
        201:
          description: claim created

components:
  schemas:
    Pong:
      type: object
      required:
      - pong
      properties:
        pong:
          type: string
          example: pong

    SourceInput:
      type: object
      required:
      - name
      - summary
      - tags
      - uri
      properties:
        name:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
            validate: nonempty
        summary:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
            validate: nonempty
        tags:
          type: string
          x-oapi-codegen-extra-tags:
            validate: nonempty,nospace
            binding: required
        uri:
          type: string
          x-oapi-codegen-extra-tags:
            validate: httpsurl
            binding: required

    SourcePatchInput:
      type: object
      properties:
        name:
          type: string
          nullable: true
          x-oapi-codegen-extra-tags:
            validate: omitnil,nonempty
        summary:
          type: string
          nullable: true
          x-oapi-codegen-extra-tags:
            validate: omitnil,nonempty
        tags:
          type: string
          nullable: true
          x-oapi-codegen-extra-tags:
            validate: omitnil,nospace,nonempty

    Source:
      type: object
      required:
      - name
      - score
      - summary
      - tags
      - uri
      - uriDigest
      properties:
        name:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        score:
          type: number
          format: double
          x-oapi-codegen-extra-tags:
            binding: required
        uriDigest:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
            gorm: primaryKey
        summary:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        tags:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        uri:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required

    CreateSourceResponse:
      type: object
      required:
      - uriDigest
      properties:
        uriDigest:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required

    ClaimInput:
      type: object
      required:
      - sourceUriDigest
      - title
      - uri
      properties:
        sourceUriDigest:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        summary:
          type: string
          x-oapi-codegen-extra-tags:
        title:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        uri:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required

    Claim:
      type: object
      required:
      - sourceUriDigest
      - summary
      - title
      - uri
      - uriDigest
      - checked
      - validity
      properties:
        sourceUriDigest:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        summary:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        title:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        uri:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
        uriDigest:
          type: string
          x-oapi-codegen-extra-tags:
            binding: required
            gorm: primaryKey
        checked:
          type: boolean
          default: false
          x-oapi-codegen-extra-tags:
            binding: required
        validity:
          type: boolean
          default: false
          x-oapi-codegen-extra-tags:
            binding: required