openapi: 3.0.0
info:
  title: Source Score Microservice
  description: An application to rate sources based on the validity of their claims
  version: 0.0.1

paths:
  /ping:
    get:
      responses:
        200:
          description: pong response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'

components:
  schemas:
    Pong:
      type: object
      required:
        - pong
      properties:
        pong:
          type: string
          example: pong