name: Acceptance Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install k3d
      run: make install-k3d-cli

    - name: Setup test CNPG
      env:
        APP_USER_PASSWORD: ${{ vars.APP_USER_PASSWORD }}
      run: echo "$APP_USER_PASSWORD"

    - name: Setup test CNPG
      env:
        APP_USER_PASSWORD: ${{ vars.APP_USER_PASSWORD }}
        SUPER_USER_PASSWORD: ${{ secrets.SUPER_USER_PASSWORD }}
      run: make local-pg-setup

    - name: Run acceptance tests
      run: make acceptance-tests
